### ISSUE TITLE
你好，程序在编译时报错

### ISSUE THREAD

**Issue by sunny0616** [duan602728596/qqtools#10]
在npm run start时，发生了报错，
具体报错信息如下，好像是babel-loader这个依赖包的问题？实在找不到答案，望解答，谢谢！
ERROR in ./src/router/Routers.js 16:38
Module parse failed: Unexpected token (16:38)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
| import Index from '../modules/Index/Layout';
> const LoginBundle = asyncModule(() => import('../modules/Login/Layout'));
| const OptionBundle = asyncModule(() => import('../modules/Option/Layout'));
| const KouDai48Bundle = asyncModule(() => import('../modules/KouDai48/Layout'));
 @ ./src/index.js 12:0-39 22:61-68
 @ multi ./src/index.js

**Comment by duan602728596** [comment]
我刚才试了一下，编译是正常的。你是在哪个文件夹编译的？node环境是什么？用的是npm还是yarn？

**Comment by sunny0616** [comment]
> 我刚才试了一下，编译是正常的。你是在哪个文件夹编译的？node环境是什么？用的是npm还是yarn？

在app下编译的，node版本是v10.15.3，用的npm

**Comment by duan602728596** [comment]
你需要先运行命令`npm run dll`，然后运行命令`npm start`。

**Comment by sunny0616** [comment]
> 你需要先运行命令`npm run dll`，然后运行命令`npm start`。你可以重新装一下依赖包，或者`babel-loader`。如果还不好使，使用yarn替代一下npm。

之前run过dll了，也重新装过babel-loader了，我再update依赖包和用yarn试试，谢谢解答！

**Comment by duan602728596** [comment]
现在好使了吗？

**Comment by sunny0616** [comment]
> 现在好使了吗？

刚刚用了yarn可以了！！！谢谢聚聚耐心解答~

**Comment by duan602728596** [comment]
那可能就是版本依赖的问题了

**Comment by sunny0616** [comment]
> 那可能就是版本依赖的问题了

是的是的，之前觉得是依赖的问题，谷歌了半天安了很多依赖也不行，没想到yarn就这么好使

**Comment by duan602728596** [comment]
好使就行了
