### ISSUE TITLE
控台可以接受到消息，但是QQ没有反应

### ISSUE THREAD

**Issue by LUDA-LLX** [duan602728596/qqtools#101]
## 错误报告

<
![A RE~L$SKL%QUG3(7`M$U1J(1)_edit_426024670392804](https://user-images.githubusercontent.com/59410226/132993224-f5fd41dd-3a1c-4181-bda0-ab59bdfee077.png)
>

## 使用环境

- 操作系统：win10
- 软件版本：mirai-api-http-v2. 3. 0
- 插件mirai-console-2. 7. 1-dev-1

**Comment by duan602728596** [comment]
软件可以正常使用，不是软件的问题。检查一下mirai用的有没有问题。
1、QQ号等级低的话，最好挂一阵后再用，避免被风控。
2、检查mirai-api-http的配置。

**Comment by LUDA-LLX** [comment]
setting.yml文件的配置有模板吗，我用的是默认的配置，QQ风控应该不会 用的是自己常用的QQ测试的

**Comment by duan602728596** [comment]
看文档https://www.yuque.com/bbkkbkk/qqtools/rlphu0

**Comment by LUDA-LLX** [comment]
重新设置了一下配置还是不行，这是miari控制台的信息, 也没有红色报错(◞‸◟ )![N(_)O(5$HIT(MZO@L74JCVL](https://user-images.githubusercontent.com/59410226/132995283-d53194e0-4f29-4e73-b31c-826ff22ece6e.png)

**Comment by duan602728596** [comment]
换个端口，比如11034这种不常用的端口。

**Comment by LUDA-LLX** [comment]
OK, 已解决，谢谢
