### ISSUE TITLE
统计鸡腿数

### ISSUE THREAD

**Issue by wykbon** [duan602728596/qqtools#103]
大佬你好，请问现在是否有统计某xox当月鸡腿数量的功能？ 因为现在口袋都看不到鸡腿数量了~
若没有，之后是否有计划添加呢？
辛苦啦

**Comment by duan602728596** [comment]
口袋都下了，我更拿不到了

**Comment by wykbon** [comment]
> 口袋都下了，我更拿不到了

如果是抓当次直播的礼物总数呢？ 就是这次直播xox一共收到多少个礼物，或者鸡腿总额也行。

**Comment by duan602728596** [comment]
> > 口袋都下了，我更拿不到了
> 
> 如果是抓当次直播的礼物总数呢？ 就是这次直播xox一共收到多少个礼物，或者鸡腿总额也行。

这个都需要看有没有接口支持。如果你在直播里查不到，那就拿不到了
