### ISSUE TITLE
是否可以增加抖音提醒

### ISSUE THREAD

**Issue by wykbon** [duan602728596/qqtools#109]
## 你期望的功能是怎样的？
请问能增加抖音提醒功能吗？ 
另外微博可以每个人两个号吗？想把她们公开小号也加上。 谢谢聚聚！

**Comment by duan602728596** [comment]
微博小号的话，你可以配置多个。
抖音的话，不是很想加，因为一是没有接口，二是头条的反爬强度很高，容易被拉黑。

**Comment by wykbon** [comment]
> 有接口，二是头条的反爬强度很高，容易被拉黑。

好的，谢谢大佬。
另外想问下是否可以一键登入多个房间，因为现在添加的xox有点多。有时候卡段又要重新找电脑连上服务器一个个点。
