### ISSUE TITLE
这个工具可以回去获取QQ群成员信息吗？

### ISSUE THREAD

**Issue by yoyo-sincerely** [duan602728596/qqtools#11]
如题
获取的信息包括 qq号，入群时间等。

**Comment by duan602728596** [comment]
我这个是通过CoolQ HTTP API插件监听群信息的，https://cqhttp.cc/docs/4.10/#/API?id=get_group_member_info-%E8%8E%B7%E5%8F%96%E7%BE%A4%E6%88%90%E5%91%98%E4%BF%A1%E6%81%AF可以获取到
