### ISSUE TITLE
添加适配

### ISSUE THREAD

**Issue by Air433up** [duan602728596/qqtools#114]
## 这个功能解决了什么问题？

大佬，能否添加一下对go-cqhttp的适配，感觉这个比mirai要好用点，内存占用也小，而且好像和oicq差不多，我使用go-cqhttp配置的时候选用oicq类型能进入房间，但就是监听不到消息，应该改一点就能用

## 你期望的功能是怎样的？

适配go-cqhttp

**Comment by duan602728596** [comment]
已适配。
