### ISSUE TITLE
其他成员进出房间未捕捉到的问题

### ISSUE THREAD

**Issue by HibariSun** [duan602728596/qqtools#118]
## 错误报告
聚聚你好。我在两台不同的电脑上运行这个程序，结果都出现了有其他成员进入kdfj没有捕捉到的情况。就像图中这样，0:12的时候其他成员进入该房间的时候有一个没有捕捉到。这样漏捕捉到其他xox进入房间的情况这两天发生次数挺多的，请问下可能是什么问题造成的？
![微信图片_20211211113457](https://user-images.githubusercontent.com/79096889/145662705-625035d9-1576-4e24-b593-7467b0931062.jpg)
![微信图片_20211211113511](https://user-images.githubusercontent.com/79096889/145662708-145e01a4-463b-46bc-9405-2bbccef48430.jpg)

**Comment by duan602728596** [comment]
在查询间隔时间之内离开了就会找不到，而且大部分看一眼就走，不会停留很长时间

**Comment by Air433up** [comment]
> 在查询间隔时间之内离开了就会找不到，而且大部分看一眼就走，不会停留很长时间

那能否将查询间隔调小，我曾尝试将间隔调成10s再编译使用也未见明显问题

**Comment by Air433up** [comment]
> 就是怕太频繁了

好的
