### ISSUE TITLE
定时发送的功能可以给个示例嘛，介绍没太看懂 多谢~

### ISSUE THREAD

**Issue by qzq1994** [duan602728596/qqtools#12]
如果不配置该位置，则用“*”占位；

多个时间段用“,”分割，比如2,4,6表示；

连续时间段用类似2-6表示；

每隔多长时间，可以用类似*/5表示；

每个规则不要有空格，规则和规则之间要有空格。

**Comment by duan602728596** [comment]
比如每天的12:00发送一次消息：`0 0 12 * * *`。
比如每到30秒发送一次消息：`30 * * * * *`。
比如每5分钟发送一次消息：`0 */5 * * * *`。
比如每个月的2、4、6号：`* * * 2,4,6 * *`。
比如每个月的2到6号：`* * * 2-6 * *`。

底层用的是[node-schedule](https://github.com/node-schedule/node-schedule)。
