### ISSUE TITLE
无法接收图片

### ISSUE THREAD

**Issue by LUDA-LLX** [duan602728596/qqtools#122]
## 错误报告

现在接收不到图片了，是不是要更新mirai了
## 使用环境

- 操作系统：
- 软件版本：

**Comment by duan602728596** [comment]
可以试试更新吧，这个不是我的问题

**Comment by HibariSun** [comment]
我试了下把mirai-console,mirai-console-terminal.mirai-core-all三个文件升级到2.9.1以后就能发送图片了
