### ISSUE TITLE
mirai更新后登陆异常

### ISSUE THREAD

**Issue by NeamZhang** [duan602728596/qqtools#124]
## 错误报告

最近发不出图片（log中有但发不出来），看了mirai那边是版本问题就升级了一下。
重新登陆时，qq号可以正常登录，但是原先配置好的机器人进不去，点“登陆”以后没有任何提示。
又尝试换回mirai旧版本，一切正常。请问大佬是不是适配版本问题？

## 使用环境

- 操作系统：
- 软件版本：

**Comment by NeamZhang** [comment]
> ## 错误报告
> 最近发不出图片（log中有但发不出来），看了mirai那边是版本问题就升级了一下。 重新登陆时，qq号可以正常登录，但是原先配置好的机器人进不去，点“登陆”以后没有任何提示。 又尝试换回mirai旧版本，一切正常。请问大佬是不是适配版本问题？
> 
> ## 复现步骤
> ## 预期行为
> ## 使用环境
> * 操作系统：
> * 软件版本：
![MessageCenterUI_XdcKfLwn33](https://user-images.githubusercontent.com/73150263/148158663-19e64135-f0e3-4a99-a11c-bc9d7a17ac90.png)
控制台显示是连接问题

**Comment by BloodBerserker** [comment]
我也是这样，使用mirai2.9.0的傻瓜包，用mirai-api-http-2.3.3

**Comment by duan602728596** [comment]
试了一下，没问题。你自己检查一下吧，换个端口

**Comment by NeamZhang** [comment]
尝试几次，发现始终无法打开设定给mirai的端口。研究后发现是mirai-api-http版本从1.x变为2.x之后，配置文件的格式变了，重写配置文件后回归正常。
