### ISSUE TITLE
控制台没获取的口袋消息

### ISSUE THREAD

**Issue by KOUymA** [duan602728596/qqtools#125]
## 错误报告

登录后，能看到进入聊天室
![image](https://user-images.githubusercontent.com/72074577/148024635-1cd31d44-52c3-4ae6-af05-7a92f109de58.png)
但是后续的消息在控制台中都收不到

## 复现步骤

1.登录mirai
![image](https://user-images.githubusercontent.com/72074577/148025542-a2600609-de00-473f-b7d7-1f5710ca3635.png)
2.登录配置
![image](https://user-images.githubusercontent.com/72074577/148025561-3b376d02-a3a0-43e9-8560-8aed75b5e8b6.png)

## 预期行为

能够收到消息

## 使用环境

- 操作系统：windows server 2016
- 软件版本：4.8.0

**Comment by duan602728596** [comment]
你检查一下你的房间ID吧
