### ISSUE TITLE
控制台出现getChatroomMember报错

### ISSUE THREAD

**Issue by KOUymA** [duan602728596/qqtools#128]
## 错误报告

![image](https://user-images.githubusercontent.com/72074577/157703690-2729c30e-ce83-4c3a-a3bc-a630ec49f1c0.png)
出现错误后 无法收到推送消息

## 复现步骤

运行了一段时间以后没收到推送，控制台出现这个报错
控制台可以获取到qq的信息但是推送不成功没反应
重启以后，依然可以复现

## 使用环境

- 操作系统：windows server 2016
- 软件版本：4.8.0

**Comment by KOUymA** [comment]
突然好了。。。

**Comment by HibariSun** [comment]
你能收到房间消息吗，要是你控制台上能看到房间消息，QQ上没有可能是你QQ号被风控了

**Comment by KOUymA** [comment]
> 你能收到房间消息吗，要是你控制台上能看到房间消息，QQ上没有可能是你QQ号被风控了



> 你能收到房间消息吗，要是你控制台上能看到房间消息，QQ上没有可能是你QQ号被风控了

很奇怪 能正常登上qq也能正常群聊私聊 今天大部分推送收不到 但是可以收到某几条推送  发log这种指令 服务信息也推送不成功

**Comment by duan602728596** [comment]
这个是云信sdk报出的错误，你看看你的房间号配置是否正确

**Comment by KOUymA** [comment]
> 这个是云信sdk报出的错误，你看看你的房间号配置是否正确

![image](https://user-images.githubusercontent.com/72074577/157828567-8d7a1330-ca16-4c4d-970a-256c5cefb588.png)
应该没问题吧 配置一直都没改过 之前两个月都是没问题的

**Comment by HibariSun** [comment]
> > 你能收到房间消息吗，要是你控制台上能看到房间消息，QQ上没有可能是你QQ号被风控了
> 
> > 你能收到房间消息吗，要是你控制台上能看到房间消息，QQ上没有可能是你QQ号被风控了
> 
> 很奇怪 能正常登上qq也能正常群聊私聊 今天大部分推送收不到 但是可以收到某几条推送 发log这种指令 服务信息也推送不成功

我之前碰到收不到推送一般就是账号被风控了，服务器上QQ挂个几天再试试吧

**Comment by KOUymA** [comment]
> > > 你能收到房间消息吗，要是你控制台上能看到房间消息，QQ上没有可能是你QQ号被风控了
> > 
> > 
> > 很奇怪 能正常登上qq也能正常群聊私聊 今天大部分推送收不到 但是可以收到某几条推送 发log这种指令 服务信息也推送不成功
> 
> 我之前碰到收不到推送一般就是账号被风控了，服务器上QQ挂个几天再试试吧

应该不是被风控 这个号很久得了 现在没做任何操作 推送又好了。。。。
