### ISSUE TITLE
聚聚留言板删除消息会播报

### ISSUE THREAD

**Issue by x12121** [duan602728596/qqtools#13]
聚聚留言板删除消息会播报

：未知信息类型，请联系开发者。
数据：{"messageType":"DELETE","targetId":"6d81e51a-8a6a-46ca-a3bd-e908167822dc"}
时间：2020-06-04 15:04:00

**Comment by duan602728596** [comment]
目前暂时会监听所有消息，因为换了接口，数据会和原来的接口有区别，我需要获取一些信息来知道数据结构，然后再处理




| |
段昊辰
|
|
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

在2020年06月04日 15:12，x12121 写道：

聚聚留言板删除消息会播报

：未知信息类型，请联系开发者。
数据：{"messageType":"DELETE","targetId":"6d81e51a-8a6a-46ca-a3bd-e908167822dc"}
时间：2020-06-04 15:04:00
