### ISSUE TITLE
请问v4.9.0版本的登录方式变了吗

### ISSUE THREAD

**Issue by longgu2021** [duan602728596/qqtools#130]
这是4.8的

![image](https://user-images.githubusercontent.com/84063573/179442887-252493cb-bc33-498b-99b0-ffebe22a9577.png)

4.9变成了mcl的
![image](https://user-images.githubusercontent.com/84063573/179442914-420eb9d7-a205-4fec-b029-16ba30b9c31d.png)

还能该回原来的登录方式吗

**Comment by duan602728596** [comment]
1. mcl和原来的登录方式是一样的，因为mcl是原始登录方式的封装。
2. 原始的命令登录的方式在最新的版本会出错，这也是我为啥删除了原来的登录的原因，因为真的不好使了。
3. 不推荐用这个登录，因为在window系统下子进程的嵌套会出现问题，mac下没问题。
4. 现在这个版本是一个不太好的版本，将来可能还会改。
