### ISSUE TITLE
编译报错报错

### ISSUE THREAD

**Issue by Air433up** [duan602728596/qqtools#132]
## 错误报告

![image](https://user-images.githubusercontent.com/60246381/182141022-dabc8b21-be1c-4b41-a215-558f06750939.png)

## 复现步骤

编译软件时到达92%后报错，重复安装依赖依旧报错，可以排除依赖问题，而且你releases中也只有源码，机器人未构建软件，是否代码中存在变量定义错误导致报错
## 使用环境

- 操作系统：win10
- 软件版本：4.10.0

**Comment by duan602728596** [comment]
Node版本太低，需要升级版本
