### ISSUE TITLE
搭建在服务器上就无法运行

### ISSUE THREAD

**Issue by LUDA-LLX** [duan602728596/qqtools#134]
![IMG_20220826_003015](https://user-images.githubusercontent.com/59410226/186720604-7702513d-e7bb-4d53-ba63-2cc220bb5df5.jpg)

## 复现步骤
请帮忙看看这个报错是什么意思呢，在自己电脑上就可以运行，到服务器上就不行，无法配置房间信息，也无法导入

## 使用环境

- 操作系统：win7
- 软件版本：64

**Comment by duan602728596** [comment]
在控制台中把数据库数据删除了试试。

**Comment by duan602728596** [comment]
或者也有可能是系统的问题。
