### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by Air433up** [duan602728596/qqtools#135]
## 错误报告

口袋版本更新，机器人已经获取不到消息了
## 预期行为

恳请大佬适配新版
## 使用环境

- 操作系统：Win11
- 软件版本：4.8.0

**Comment by duan602728596** [comment]
可以测一测了

**Comment by Air433up** [comment]
@duan602728596 进出房间和xox发言消息都没有，但是翻牌消息有

**Comment by duan602728596** [comment]
serverId填错了吧

**Comment by Air433up** [comment]
@duan602728596 我以为还是以前的参数，改了后xox发言有了，但是进出房间信息没有

**Comment by duan602728596** [comment]
没有进出消息了

**Comment by onlyzqy** [comment]
<img width="562" alt="无标题" src="https://user-images.githubusercontent.com/44560939/187245318-a77418bb-df47-4e92-b72f-0890aabdd609.png">
<img width="262" alt="无标题1" src="https://user-images.githubusercontent.com/44560939/187245704-5036b8a7-1d50-41af-9c3b-c11297b2bbb7.png">
是按文件中的serverid填的但是就一直收不到消息，控制台反馈看起来像是没能成功接入房间

**Comment by longgu2021** [comment]
想问下现在都需要口袋小号了吗  一个口袋小号可以用来监听最多几个成员房间呢

**Comment by spicyrnilk** [comment]
> <img alt="无标题" width="562" src="https://user-images.githubusercontent.com/44560939/187245318-a77418bb-df47-4e92-b72f-0890aabdd609.png">
> 
> <img alt="无标题1" width="262" src="https://user-images.githubusercontent.com/44560939/187245704-5036b8a7-1d50-41af-9c3b-c11297b2bbb7.png">
> 
> 是按文件中的serverid填的但是就一直收不到消息，控制台反馈看起来像是没能成功接入房间

同样的问题。

**Comment by studyren** [comment]
> <img alt="无标题" width="562" src="https://user-images.githubusercontent.com/44560939/187245318-a77418bb-df47-4e92-b72f-0890aabdd609.png">
> 
> <img alt="无标题1" width="262" src="https://user-images.githubusercontent.com/44560939/187245704-5036b8a7-1d50-41af-9c3b-c11297b2bbb7.png">
> 
> 是按填的但就收不到消息的服务器id，看起来好像没能成功地完成访问房间的消息

要登录的那个账户有关注xox，我也是遇到这个问题，然后有关注的就有返回信息，没关注的直接配置就返回不了信息

**Comment by spicyrnilk** [comment]
晚上试一下。
感谢帮助！


发自我的iPhone

在 2022年8月31日，08:59，studyren ***@***.***> 写道：

﻿

[无标题]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F44560939%2F187245318-a77418bb-df47-4e92-b72f-0890aabdd609.png&data=05%7C01%7C%7C8f58e2713b82458c8a5a08da8aec13f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637975043823665567%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XhLOsua5wIFnm91Ncgbexyi8%2FqV%2BpI2%2BOklydXKgMwg%3D&reserved=0> [无标题1] <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F44560939%2F187245704-5036b8a7-1d50-41af-9c3b-c11297b2bbb7.png&data=05%7C01%7C%7C8f58e2713b82458c8a5a08da8aec13f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637975043823665567%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Gh6cXD3kaKxRYgibtgsS1PyFaLt2f7Tt8N2LsDKT%2BM8%3D&reserved=0>

是按填的但就收不到消息的服务器id，看起来好像没能成功地完成访问房间的消息

要登录的那个账户有关注xox，我也是遇到这个问题，然后有关注的就有返回信息，没关注的直接配置就返回不了信息
