### ISSUE TITLE
更新新版口袋之后，上下线/进出房间播报似乎失效了

### ISSUE THREAD

**Issue by LycOrange** [duan602728596/qqtools#137]
## 错误报告

更新新版口袋之后，上下线/进出房间播报似乎失效了

## 复现步骤

更新版本后，仅在原有配置上新增了serverId，其余并未改动

## 预期行为

显示成员上下线/进出房间

## 使用环境

- 操作系统：windows server 2012R2
- 软件版本：v4.11.0 beta0

**Comment by duan602728596** [comment]
没有了，配置上没有的就是不支持原来的功能
