### ISSUE TITLE
回复礼物消息报错

### ISSUE THREAD

**Issue by lanfeng-shui** [duan602728596/qqtools#139]
## 错误报告

![image](https://user-images.githubusercontent.com/81756923/197314809-bd164c3a-f513-48ba-97fb-7b8ded969c2b.png)

## 复现步骤

回复礼物消息

## 预期行为

正常显示

## 使用环境

- 操作系统：win11 22h2
- 软件版本：4.11.0-beta.1

**Comment by duan602728596** [comment]
已修复
