### ISSUE TITLE
推送吞消息

### ISSUE THREAD

**Issue by Nothatcold07** [duan602728596/qqtools#14]
大佬您好，我第一次用qqtools，设置完后,qqtools推送的时候发现xox有的发言记录并没有都被推送到QQ群，会被漏掉。，不知道是什么原因了。

**Comment by duan602728596** [comment]
什么类型的发言？比如是视频还是翻牌什么的？




| |
段昊辰
|
|
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

在2020年06月05日 23:38，Nothatcold07 写道：

大佬您好，我第一次用qqtools，设置完后,qqtools推送的时候发现xox有的发言记录并没有都被推送到QQ群，会被漏掉。，不知道是什么原因了。

**Comment by Nothatcold07** [comment]
> 什么类型的发言？比如是视频还是翻牌什么的？ | | 段昊辰 | | 邮箱：duanhaochen@126.com | 签名由 网易邮箱大师 定制 在2020年06月05日 23:38，Nothatcold07 写道： 大佬您好，我第一次用qqtools，设置完后,qqtools推送的时候发现xox有的发言记录并没有都被推送到QQ群，会被漏掉。，不知道是什么原因了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

语音文字都有被吞的现象

**Comment by duan602728596** [comment]
> > 什么类型的发言？比如是视频还是翻牌什么的？ | | 段昊辰 | | 邮箱：[duanhaochen@126.com](mailto:duanhaochen@126.com) | 签名由 网易邮箱大师 定制 在2020年06月05日 23:38，Nothatcold07 写道： 大佬您好，我第一次用qqtools，设置完后,qqtools推送的时候发现xox有的发言记录并没有都被推送到QQ群，会被漏掉。，不知道是什么原因了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 语音文字都有被吞的现象

你用的是最新版吗？错误的时候有发送错误信息吗？

**Comment by Nothatcold07** [comment]
> > > 什么类型的发言？比如是视频还是翻牌什么的？ | | 段昊辰 | | 邮箱：[duanhaochen@126.com](mailto:duanhaochen@126.com) | 签名由 网易邮箱大师 定制 在2020年06月05日 23:38，Nothatcold07 写道： 大佬您好，我第一次用qqtools，设置完后,qqtools推送的时候发现xox有的发言记录并没有都被推送到QQ群，会被漏掉。，不知道是什么原因了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 语音文字都有被吞的现象
> 
> 你用的是最新版吗？错误的时候有发送错误信息吗？

对的 v3.40-beta.1 这个版本
错误的时候没有发送错误信息直接漏掉了 倒是昨天又有弹出一个 未知信息类型，请联系开发者。这个东西..
因为github上不方便举例讲 我就把例子的截图发你126邮箱了

**Comment by duan602728596** [comment]
未知信息类型已经解决了，是类型不一致的问题。
吞消息的情况我还没遇到，你可以去qq的log里面看一下是否是被QQ吞掉了。
如果不是被QQ吞掉了，那就是使用SDK的问题了

**Comment by duan602728596** [comment]
可以试试使用rc版本，口袋的接口添加了验证方法

**Comment by Nothatcold07** [comment]
> 可以试试使用rc版本，口袋的接口添加了验证方法

最新的版本已经不吞消息了 辛苦大佬了
