### ISSUE TITLE
只能获取直播信息，无法获取成员房间发言

### ISSUE THREAD

**Issue by TBYBY** [duan602728596/qqtools#142]
## 错误报告

![image](https://user-images.githubusercontent.com/47664362/201710846-74e8b3cd-a6fc-4036-a741-5963b52d13c9.png)
![image](https://user-images.githubusercontent.com/47664362/201710987-951f4ea9-1fea-46f3-b0cb-6a1bba2d5ae1.png)
正确登陆了成员房间，但是无法获取成员房间发言。

## 预期行为
希望能够获取成员上下线以及房间的发言信息

## 使用环境
软件版本：
java : 11
maria : 2.13.0
api-http: 2.6.2

登录配置
使用 口袋IM登录 进行监听，非游客模式

setting.yml 配置
![image](https://user-images.githubusercontent.com/47664362/201713581-7f616148-cf9a-4f97-816c-bf9d43e85e40.png)

大佬能帮忙看下是什么问题吗，感谢

**Comment by duan602728596** [comment]
下载4.11.0版本

**Comment by TBYBY** [comment]
那想问一下，是什么原因导致的呢，我之前下载的qqtools是4.10.0版本

**Comment by duan602728596** [comment]
> 那想问一下，是什么原因导致的呢，我之前下载的qqtools是4.10.0版本

新版口袋房间用的sdk换了

**Comment by TBYBY** [comment]
了解
