### ISSUE TITLE
ubuntu22.04系统，无法添加配置

### ISSUE THREAD

**Issue by onlyforqiong** [duan602728596/qqtools#145]
## 错误报告

ubuntu22.04系统下，点击添加配置软件会全白
![image](https://user-images.githubusercontent.com/73653393/213609794-22475adc-4185-431a-b317-2b5bb95d7c79.png)
无法打开开发者模式，会显示报错
[13122:0120/111218.310882:ERROR:CONSOLE(1)] "Uncaught (in promise) RangeError: First argument to Intl.Locale constructor can't be empty or missing", source: devtools://devtools/bundled/core/i18n/i18n.js (1)

## 复现步骤

1. 在解压后的目录中输入./qq_tools打开软件
2. 点击开发者工具
3. 终端中便会显示第二个报错
4. 点击登陆配置->点击添加配置，出现软件全白错误

## 使用环境

- 操作系统：ubuntu22.04
- 软件版本：4.11.0

**Comment by duan602728596** [comment]
开发者模式是electron自己的问题，这个只能升级electron版本看看了。

**Comment by duan602728596** [comment]
全白有可能是数据格式错误，如果控制台打不开，只能等我添加错误边界来处理了。

**Comment by onlyforqiong** [comment]
> 全白有可能是数据格式错误，如果控制台打不开，只能等我添加错误边界来处理了。

我在windows下配置成功了，我尝试将windows的配置文件进行稍微的修改用在ubuntu下，但是在登陆的时候报错
这时我修改后的文件
![image](https://user-images.githubusercontent.com/73653393/213620832-dac73679-696e-41bf-9514-927adc1109a4.png)
这是在账号登陆选项后点击登陆的报错，使用mcl终端能够成功登陆
![image](https://user-images.githubusercontent.com/73653393/213621264-af00c8fc-c2ca-46e4-8323-a01915efb244.png)

**Comment by duan602728596** [comment]
session失败这就是mirai-http-plugin这边配置可能出现了问题了，登录失败导致的，可以试试改一下接口和authkey试试
