### ISSUE TITLE
登录后建立IM连接提示：订阅服务器失败

### ISSUE THREAD

**Issue by ligohan** [duan602728596/qqtools#146]
## 错误报告

- 登录后建立IM连接提示：订阅服务器失败
- 已尝试更换网络环境、更换软件版本

![image](https://user-images.githubusercontent.com/24909679/228175107-11fc21d5-07fb-44a0-8c5b-bb623c39e508.png)

## 使用环境

- 操作系统：macOS 13.3
- 软件版本：4.3.10

**Comment by duan602728596** [comment]
关注了么？

**Comment by ligohan** [comment]
关注了的，账号也换过了

**Comment by duan602728596** [comment]
别的账号也不好使吗？

**Comment by spicyrnilk** [comment]
导入房间信息试试。
