### ISSUE TITLE
按登录没反应

### ISSUE THREAD

**Issue by Singx9** [duan602728596/qqtools#149]
设置好之后，按登录时没反应，请问这个要怎么解决啊？
![image](https://user-images.githubusercontent.com/23257087/233544499-d6c5f137-b05f-4f73-8fe5-6f0ea2c6bb89.png)

**Comment by duan602728596** [comment]
你看看network，有没有失败的请求。

**Comment by Singx9** [comment]
感谢解答！看了network是端口已被占用，修改之后连上了！
