### ISSUE TITLE
为什么我找不到setting.yml文件

### ISSUE THREAD

**Issue by AMI48Yaohun** [duan602728596/qqtools#150]
[](url)
![image](https://github.com/duan602728596/qqtools/assets/117826075/9fcbeaae-b949-40d7-aa4d-5d585d45373c)

**Comment by duan602728596** [comment]
你没用mirai-api-http的插件吧

**Comment by AMI48Yaohun** [comment]
![image](https://github.com/duan602728596/qqtools/assets/117826075/6b90728e-3b92-47a3-8c80-16a67c48e841)
登录失败怎么搞

**Comment by AMI48Yaohun** [comment]
> 



> 你没有用mirai-api-http的插件吧

登录失败怎么搞
![image](https://github.com/duan602728596/qqtools/assets/117826075/32300cb9-1564-44ad-ba60-c5786d7c287d)

**Comment by duan602728596** [comment]
升级到最新版本或养号

**Comment by AMI48Yaohun** [comment]
> 升级到最新版本或养号

请问怎么升级

> 升级到最新版本或养号

**Comment by duan602728596** [comment]
这个你需要看mirai的文档
