### ISSUE TITLE
工具台报错WebSocket connection to ws

### ISSUE THREAD

**Issue by Luppp17** [duan602728596/qqtools#151]
![屏幕截图 2023-06-02 145829](https://github.com/duan602728596/qqtools/assets/111509818/49519a1e-b646-4a24-bd0e-66384fcf9128)
![屏幕截图 2023-06-02 150328](https://github.com/duan602728596/qqtools/assets/111509818/bebe506b-61db-44d5-9c65-271214aac39a)
你好，因为完全不懂这方面，按照教程手册到这步配置websocket的时候有些不明白，搜索了相关教程
1、报错是因为websockt配置出错了吗？
2、不确定host、port这里的值应该填什么，是根据自己电脑情况来填吗？怎么知道要填什么？host的值我尝试了“localhost”、“8080”，使用“0.0.0.0”的时候CMD文件才运行成功。
“0.0.0.0”的值是我百度搜来尝试的
3、还想问下qqtools、48tools更新了是只用下载main分支的压缩包替换掉旧的文件就行了吗？

**Comment by duan602728596** [comment]
对，port你配置的是18876，但是qqtools里是8080。
host不需要填，port就填mirai配置的port。
新版就是最新的压缩包。

**Comment by Luppp17** [comment]
![屏幕截图 2023-06-02 153154](https://github.com/duan602728596/qqtools/assets/111509818/b7a3ee94-8446-40cc-8e7f-dd15a5299c23)
![屏幕截图 2023-06-02 153010](https://github.com/duan602728596/qqtools/assets/111509818/5af3ee6e-b94b-4f22-92b7-6b786b1e3af0)
![屏幕截图 2023-06-02 153314](https://github.com/duan602728596/qqtools/assets/111509818/ac6df8ea-aa71-47bf-b184-23da77ecf396)
还是报错，我setting.yml里写的有问题吗

**Comment by duan602728596** [comment]
这是别的问题，但是看你这个错误我不好说错误在哪

**Comment by Luppp17** [comment]
啊可以说吗
我搜了也没搜到相关的解决方法

**Comment by duan602728596** [comment]
你应该是哪个配置错了，你把所有的配置都关掉，然后一个一个打开试试。

**Comment by Luppp17** [comment]
配置关掉是指setting.yml里true、false的值改一下吗？还是数字啥的也要改？刚刚试了半天也没找出问题在哪

**Comment by duan602728596** [comment]
先测试qq能否连上，即只配置qq，然后看群里输入log有没有消息发出。然后挨个开启配置，比如口袋、微博之类的。

**Comment by Luppp17** [comment]
![屏幕截图 2023-06-02 162500](https://github.com/duan602728596/qqtools/assets/111509818/8acc4ddc-f1f9-4465-8e74-739826a988e6)
![屏幕截图 2023-06-02 162605](https://github.com/duan602728596/qqtools/assets/111509818/735c9421-c2ee-4118-96ee-cbdc29c08cd4)
![屏幕截图 2023-06-02 162729](https://github.com/duan602728596/qqtools/assets/111509818/39582bee-625b-4a84-872b-55b728f52f31)
![屏幕截图 2023-06-02 162959](https://github.com/duan602728596/qqtools/assets/111509818/5b93cae7-4260-4bb4-bb22-a5eb4a868e51)
QQ应该是能连上的，tools里我也只配置了口袋。在群里输入log，cmd里有显示，但是群里没有消息发出

**Comment by duan602728596** [comment]
看看qq号和群号啥的对不对。然后一个一个开启配置
