### ISSUE TITLE
如何监听直播时候的弹幕礼物等

### ISSUE THREAD

**Issue by Jaffoo** [duan602728596/qqtools#153]
大佬，我也自己想搞一个机器人玩玩，正常的聊天频道我能连接上了，消息等也能正常获取，但是直播的获取不到，于是我看了一下网易云信的文档，里面有个实时互动的频道（QChatMedia），看上去就像直播用的频道，所以我用文档中的方法连接到该频道，传的是serverid和直播时频道id，但是连接不上。突然我想起了大佬开源的qqtools这个工具，于是我看了一下您的代码，但是我没找到直播时获取弹幕、礼物等相关的代码，所以发了这个issue，请教一下代码是不是我找漏了，或者请您帮忙指点一下，是不是我方法错了，我该怎么获取直播时的弹幕和礼物信息呢。

**Comment by duan602728596** [comment]
弹幕的是原NIM / Chatroom SDK。
https://github.com/duan602728596/48tools/blob/main/packages/48tools/src/pages/PlayerWindow/sdk/NimChatroomSocket.ts

**Comment by Jaffoo** [comment]
![image](https://github.com/duan602728596/qqtools/assets/86825947/002054f1-34c1-4d67-9a04-4ffe2c683a29)
大佬，又来麻烦您了，我遇到的问题是这样的，我用了官方文档的例子，也用了您的代码，都能连接上房间，但是除了连接成功的回调函数正常，其他的回调函数都有报错（如图），包括消息回调。网上我也搜了很多方法，比如用一个包通过修改.babelrc忽略严格模式，但是没有用。所以特来请教一下您出现这个问题了吗，如何解决。我用的是vue3+vite+ts。

**Comment by Jaffoo** [comment]
> 直播弹幕和礼物的是原NIM / Chatroom SDK。 https://github.com/duan602728596/48tools/blob/main/packages/48tools/src/pages/PlayerWindow/sdk/NimChatroomSocket.ts

**Comment by Jaffoo** [comment]
> ![image](https://user-images.githubusercontent.com/86825947/244946561-002054f1-34c1-4d67-9a04-4ffe2c683a29.png) 大佬，又来麻烦您了，我遇到的问题是这样的，我用了官方文档的例子，也用了您的代码，都能连接上房间，但是除了连接成功的回调函数正常，其他的回调函数都有报错（如图），包括消息回调。网上我也搜了很多方法，比如用一个包通过修改.babelrc忽略严格模式，但是没有用。所以特来请教一下您出现这个问题了吗，如何解决。我用的是vue3+vite+ts。

我测过断开连接，发现断开连接的回调函数是正常的（虽然有上面的报错），但是接收消息的回调函数没有执行，也就是接收不到任何消息，是不是少了什么步骤？

**Comment by duan602728596** [comment]
你确定你连接的是liveId吗？这个是直播的liveId。

**Comment by Jaffoo** [comment]
> 

我看文档是roomid，于是我用的是xox的roomid。。。那liveid我怎么知道呢？是不是直播发送的消息对象中包含了liveid？

**Comment by Jaffoo** [comment]
> 你确定你连接的是liveId吗？这个是直播的liveId。你最好找个在直播的来测试。

我看文档是roomid，于是我用的是xox的roomid。。。那liveid我怎么知道呢？是不是直播发送的消息对象中包含了liveid？

**Comment by duan602728596** [comment]
只能等直播时候抓liveId了
