### ISSUE TITLE
监听成员进出房间、上下线

### ISSUE THREAD

**Issue by RaphaelCS** [duan602728596/qqtools#154]
## 这个功能解决了什么问题？

实时监听成员进出房间、上下线的记录。
听说以前是有这个功能的，而且还很受欢迎，但是口袋版本更新后就没有了。

## 你期望的功能是怎样的？

如上述。

发这个issue主要是想询问一下是否有计划重新实现这些功能？
如果有，可否请教一下相关api？
如果实现上有困难，可否一起讨论一下有什么可能的实现方案？我最近正想实现这个功能，但抓了很多包都没有找到相关的api。

**Comment by duan602728596** [comment]
没有相关API，QChat没有API查询上线下线

**Comment by duan602728596** [comment]
> chatroom是有相关api可以查到房间里的实时成员列表的，作差值即可判断成员出入房间
> 
> 
> 
> 不知道qchat有没有类似的api呢？

没有
