### ISSUE TITLE
今天换了3.40最新版发现还在吞消息 不过rc昨天试了不吞了。

### ISSUE THREAD

**Issue by Nothatcold07** [duan602728596/qqtools#16]
今天换了3.40最新版发现还在吞消息 不过rc昨天试了不吞了。

**Comment by Nothatcold07** [comment]
> 用rc版本吧，sdk感觉不太稳定，rc和以前的版本没区别，只是把验证加上了 | | 段昊辰 | | 邮箱：duanhaochen@126.com | 签名由 网易邮箱大师 定制 在2020年06月10日 22:43，Nothatcold07 写道： 今天换了3.40最新版发现还在吞消息 不过rc昨天试了不吞了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

下午手滑退出登录和清除缓存后，再用账号密码登录口袋48发现登录失败，换了好几个版本都一样。账号用手机登录口袋48正常，应该没有被ban。

**Comment by duan602728596** [comment]
确实，sdk可能会有点问题，建议还是用rc版本，sdk的只是测试版本，是之前接口算法没获取到时的解决方案




| |
段昊辰
|
|
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

在2020年06月12日 16:00，Nothatcold07 写道：

用rc版本吧，sdk感觉不太稳定，rc和以前的版本没区别，只是把验证加上了 | | 段昊辰 | | 邮箱：duanhaochen@126.com | 签名由 网易邮箱大师 定制 在2020年06月10日 22:43，Nothatcold07 写道： 今天换了3.40最新版发现还在吞消息 不过rc昨天试了不吞了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

下午手滑退出登录和清除缓存后，再用账号密码登录口袋48发现登录失败，换了好几个版本都一样。账号用手机登录口袋48正常，应该没有被ban。

**Comment by Nothatcold07** [comment]
> 确实，sdk可能会有点问题，建议还是用rc版本，sdk的只是测试版本，是之前接口算法没获取到时的解决方案 | | 段昊辰 | | 邮箱：duanhaochen@126.com | 签名由 网易邮箱大师 定制 在2020年06月12日 16:00，Nothatcold07 写道： 用rc版本吧，sdk感觉不太稳定，rc和以前的版本没区别，只是把验证加上了 | | 段昊辰 | | 邮箱：duanhaochen@126.com | 签名由 网易邮箱大师 定制 在2020年06月10日 22:43，Nothatcold07 写道： 今天换了3.40最新版发现还在吞消息 不过rc昨天试了不吞了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 下午手滑退出登录和清除缓存后，再用账号密码登录口袋48发现登录失败，换了好几个版本都一样。账号用手机登录口袋48正常，应该没有被ban。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

退出之后，rc和sdk都登录不上去了..

**Comment by duan602728596** [comment]
> > 确实，sdk可能会有点问题，建议还是用rc版本，sdk的只是测试版本，是之前接口算法没获取到时的解决方案 | | 段昊辰 | | 邮箱：[duanhaochen@126.com](mailto:duanhaochen@126.com) | 签名由 网易邮箱大师 定制 在2020年06月12日 16:00，Nothatcold07 写道： 用rc版本吧，sdk感觉不太稳定，rc和以前的版本没区别，只是把验证加上了 | | 段昊辰 | | 邮箱：[duanhaochen@126.com](mailto:duanhaochen@126.com) | 签名由 网易邮箱大师 定制 在2020年06月10日 22:43，Nothatcold07 写道： 今天换了3.40最新版发现还在吞消息 不过rc昨天试了不吞了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 下午手滑退出登录和清除缓存后，再用账号密码登录口袋48发现登录失败，换了好几个版本都一样。账号用手机登录口袋48正常，应该没有被ban。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 退出之后，rc和sdk都登录不上去了..

你那是什么系统？我怀疑你ip是被拉黑了

**Comment by Nothatcold07** [comment]
> > > 确实，sdk可能会有点问题，建议还是用rc版本，sdk的只是测试版本，是之前接口算法没获取到时的解决方案 | | 段昊辰 | | 邮箱：[duanhaochen@126.com](mailto:duanhaochen@126.com) | 签名由 网易邮箱大师 定制 在2020年06月12日 16:00，Nothatcold07 写道： 用rc版本吧，sdk感觉不太稳定，rc和以前的版本没区别，只是把验证加上了 | | 段昊辰 | | 邮箱：[duanhaochen@126.com](mailto:duanhaochen@126.com) | 签名由 网易邮箱大师 定制 在2020年06月10日 22:43，Nothatcold07 写道： 今天换了3.40最新版发现还在吞消息 不过rc昨天试了不吞了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 下午手滑退出登录和清除缓存后，再用账号密码登录口袋48发现登录失败，换了好几个版本都一样。账号用手机登录口袋48正常，应该没有被ban。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 退出之后，rc和sdk都登录不上去了..
> 
> 你那是什么系统？我怀疑你ip是被拉黑了

电脑端是win10 x64 但是我特意拿小号试了下口袋48 能登录上而且发帖回复都是正常的

**Comment by duan602728596** [comment]
https://github.com/duan602728596/48debug/releases/download/v0.0.1/48debug.exe
拿这个试试能不能登陆

**Comment by Nothatcold07** [comment]
> https://github.com/duan602728596/48debug/releases/download/v0.0.1/48debug.exe
> 在命令行里运行一下，试试能不能登陆

可以  命令行里显示了ID和昵称

**Comment by duan602728596** [comment]
> > https://github.com/duan602728596/48debug/releases/download/v0.0.1/48debug.exe
> > 在命令行里运行一下，试试能不能登陆
> 
> 可以 命令行里显示了ID和昵称
可能还是被拉黑了，拉黑的是服务器的ip，因为我发现我的也被拉黑了，上了代理就好了

**Comment by duan602728596** [comment]
rc版本的pa算法已经更新
