### ISSUE TITLE
qqtools登录时无反应

### ISSUE THREAD

**Issue by Singx9** [duan602728596/qqtools#160]
## 错误报告
![image](https://github.com/duan602728596/qqtools/assets/23257087/831f3437-2120-40b1-9bd3-b4bbdd44d9b6)
![image](https://github.com/duan602728596/qqtools/assets/23257087/da3655f1-a919-468a-8d94-f34154597356)
![image](https://github.com/duan602728596/qqtools/assets/23257087/49ab435d-a2d6-4722-a7de-dfc9f7877391)

配置好登录环境，mirai正常运作也成功启用http-api。但是qqtools登录时无反应, 出现以上报错。请问哪里设置错误了吗？

## 使用环境

- 操作系统：Win 10
- 软件版本：mirai 2.15.0

**Comment by duan602728596** [comment]
检查一下配置类型呢？

**Comment by Singx9** [comment]
> 检查一下配置类型呢？

啊, 我选的是mirai，测了一下原来是要选console-test! 解决了, 成功登录了, 感谢>3

**Comment by duan602728596** [comment]
啊，那有点不对吧。你是要本地测试还是连mirai啊。

**Comment by duan602728596** [comment]
那还是有问题，console-test是本地测试的，不连接qq，只测试配置是否正确的。
等晚上看完公演我修复一下吧。

**Comment by Singx9** [comment]
> 那还是有问题，console-test是本地测试的，不连接qq，只测试配置是否正确的。 等晚上看完公演我修复一下吧。

原来这样, 辛苦了啦!
