### ISSUE TITLE
关于口袋自带的小黄脸表情

### ISSUE THREAD

**Issue by Jaffoo** [duan602728596/qqtools#163]
大佬问一下，你是怎么处理口袋小黄脸表情的，比如说这个表情
![QQ截图20231020173033](https://github.com/duan602728596/qqtools/assets/86825947/e8c90570-d2e6-401f-a1de-fc9ca0961c42)
，直接将口袋发送的文字内容输出到div中，也不会正常显示表情，而是会显示[大哭]，转发到qq也是一样的。

**Comment by duan602728596** [comment]
没有处理啊，直接就是文字显示

**Comment by Jaffoo** [comment]
好吧，我去研究一下如何处理。
