### ISSUE TITLE
gitee的地址打不开

### ISSUE THREAD

**Issue by bozzzTAT** [duan602728596/qqtools#164]
hello
gitee的仓库打不开
然后想问下 https://github.com/fuqiuluo/unidbg-fetch-qsign/releases 这个仓库内容是空的
还有别的签名服务器可以用吗

**Comment by duan602728596** [comment]
因为gitee仓库不够软件全部上传加上有一段时间比较敏感所以直接关掉public了。
那个作者被请喝茶了，所以别想了。
