### ISSUE TITLE
去除go-cqhttp连接方式中所有基于CQ码的设计

### ISSUE THREAD

**Issue by IndigoRCS** [duan602728596/qqtools#168]
## 这个功能解决了什么问题？

需求产生背景：
1. `go-cqhttp`已难以正常运行，开发者已建议大家进行迁移
2. 作为一种通用的机器人通信协议，`onebot-11`被大部分目前仍可使用的QQ机器人框架所支持，但不一定支持CQ码，[因为CQ码被认为是一种过于落后的设计，可能产生许多问题](https://whitechi73.github.io/OpenShamrock/guide/configuration.html)
3. `go-cqhttp`是一种兼容消息段数组的`onebot-11`实现

遇到的问题：
- 如果将`qqtools`使用`go-cqhttp`连接方式与不支持CQ码的`onebot`实现相连接，则：
    - `qqtools`发出的消息会在QQ中直接显示原始CQ码（比如图片消息）
    - `qqtools`接收到的传入消息（例如群消息事件），`raw_message`字段为空

## 你期望的功能是怎样的？

为支持`qqtools`自由切换到更多目前可用的QQ机器人框架，建议：
- 将`go-cqhttp`连接方式中：
    - 将使用CQ码发送消息的部分全部转换为符合`onebot-11`标准的[消息段数组](https://github.com/botuniverse/onebot-11/blob/master/message/array.md#%E6%B6%88%E6%81%AF%E6%AE%B5%E6%95%B0%E7%BB%84)
    - 将基于`raw_message`字段进行的消息判断（比如自定义命令）全部转换为基于`message`字段判断，除非`message字段`为空
- 同时，将`go-cqhttp`这一连接方式更名为`onebot-11`

**Comment by duan602728596** [comment]
目前来看OpenShamrock还是支持CQ码的？

**Comment by IndigoRCS** [comment]
OpenShamrock是支持CQ码的，但是既然它已经建议不使用CQ码了，一是说明CQ码本身有一定的使用局限性，二是说明后续也不一定会长期支持CQ码

此外，另一个目前可用的QQ机器人框架Lagrange不支持CQ码 https://github.com/LagrangeDev/Lagrange.Core/issues/58
相较于OpenShamrock，Lagrange对硬件的要求（例如不需要虚拟化、内存占用小）要少很多，是一个虽然还不完善但还算不错的替代方案

**Comment by duan602728596** [comment]
目前拉格朗日还是支持CQ码的。
由于解析处理被分散在每个要处理的字符串，所以需要重构为统一在发送方法内处理。所以要晚一些上线了。
