### ISSUE TITLE
qqtools登录失败

### ISSUE THREAD

**Issue by msyy-zj** [duan602728596/qqtools#175]
## 错误报告
登录报错415，确认了qqtools的配置和mirai-api-http中的yml文件配置也一样，请问还需要检查什么配置
![image](https://github.com/duan602728596/qqtools/assets/72148785/52f3a2f0-d0e8-4f3b-ab62-a53b786ceed6)
![image](https://github.com/duan602728596/qqtools/assets/72148785/18e71378-fa77-49f0-9a4e-5cf2e12bbcf9)
![image](https://github.com/duan602728596/qqtools/assets/72148785/eab8b1a2-ae96-4b57-9e8f-0fcb68fdf2b1)

## 复现步骤
1.启动mirai，正常登录
2.tools上添加配置
3.账号登录

## 预期行为
登录成功

## 使用环境

- 操作系统：window11
- 软件版本：qqtools 5.4.3、miria 2.6、mirai-api-http2.10.0
-

**Comment by duan602728596** [comment]
1. 在network看一下415返回了什么。
2. 使用旧版本的mirai-api-http看看是否有问题。
3. 是否使用了sign server。

**Comment by msyy-zj** [comment]
> 1. 在network看一下415返回了什么。
> 2. 使用旧版本的mirai-api-http看看是否有问题。
> 3. 是否使用了sign server。

感谢帮助，更换mirai-api-http-2.9.1版本后，可以正常登录

**Comment by duan602728596** [comment]
> > 1. 在network看一下415返回了什么。
> 
> > 2. 使用旧版本的mirai-api-http看看是否有问题。
> 
> > 3. 是否使用了sign server。
> 
> 
> 
> 感谢帮助，更换mirai-api-http-2.9.1版本后，可以正常登录

是插件的bug，估计是不会修复了。
