### ISSUE TITLE
推送信息模板变更

### ISSUE THREAD

**Issue by msyy-zj** [duan602728596/qqtools#176]
## 这个功能解决了什么问题？
![image](https://github.com/duan602728596/qqtools/assets/72148785/1b97aa1f-b303-4628-bb6a-e93b4c6e1a76)
请问一下，这个推送信息的模板可以直接在现有qtool上做变动么，还是需要去变更什么插件的配置？目前不想推送信息包含类型字样

## 你期望的功能是怎样的？
变更推送信息模板

**Comment by duan602728596** [comment]
模板目前无法变动

**Comment by msyy-zj** [comment]
好的
