### ISSUE TITLE
含口袋功能的账号登录失败

### ISSUE THREAD

**Issue by 234543746** [duan602728596/qqtools#178]
## 错误报告

![1](https://github.com/duan602728596/qqtools/assets/169711322/83a62c99-9f56-418d-81ba-793e3f176414)

## 复现步骤

Mirai正常工作，可以收到发送的信息。含口袋功能的配置无法登录，无口袋功能的配置可以成功登录，登录失败无提示
![image](https://github.com/duan602728596/qqtools/assets/169711322/6c386a9f-5a6a-461f-b115-9c8b1e003b30)

## 预期行为
登陆成功

## 使用环境

- 操作系统：win11,win10
- 软件版本：qqtools5.4.0

**Comment by duan602728596** [comment]
目前可能添加了bundleId或修改了鉴权，所以一时半会儿修改不了。

**Comment by 234543746** [comment]
嗯啊_(:з」∠)_测试了半天，感觉mirai，mirai-api-http跟其他的版本问题都可以排除掉了。大佬加油！

**Comment by duan602728596** [comment]
目前应该是UA的问题，需要动一些底层的代码。

**Comment by wtfisthatzzz** [comment]
mirai还能正常登陆吗 我的一直code=45。。风控

**Comment by 234543746** [comment]
> mirai还能正常登陆吗 我的一直code=45。。风控

可以的，现在应该都要自己挂验证了的。除口袋以外的功能都是正常使用的

**Comment by wtfisthatzzz** [comment]
> > mirai还能正常登陆吗 我的一直code=45。。风控
> 
> 可以的，现在应该都要自己挂验证了的。除口袋以外的功能都是正常使用的

9.0还能用吗

**Comment by wtfisthatzzz** [comment]
这个问题又有了，新版本5.4.5的
![image](https://github.com/duan602728596/qqtools/assets/21653867/ae1d3261-7d79-4a83-9a2d-c7017a77821e)

**Comment by 234543746** [comment]
确实，10:43的消息还是正常的，然后现在再登录也是一样的报错了，之前挂好的好像也链接断开了
![image](https://github.com/duan602728596/qqtools/assets/169711322/88434e08-91d8-4bdf-87ae-662c18dbbc42)
