### ISSUE TITLE
新版本5.4.5 口袋功能登录不上

### ISSUE THREAD

**Issue by 234543746** [duan602728596/qqtools#179]
这个问题又有了，新版本5.4.5的
![image](https://github.com/duan602728596/qqtools/assets/21653867/ae1d3261-7d79-4a83-9a2d-c7017a77821e)

_Originally posted by @wtfisthatzzz in https://github.com/duan602728596/qqtools/issues/178#issuecomment-2113915294_

**Comment by ssss3344434** [comment]
我也是这个情况

**Comment by 234543746** [comment]
追加-之前已经挂上的号暂时没受影响，新添加的会显示这个

**Comment by duan602728596** [comment]
Fixed.

**Comment by qq2104136336** [comment]
今天好像又有了，我断开连接新添加成员登录不上了

**Comment by qq2104136336** [comment]
今天好像又有了，我断开连接新添加成员登录不上了

![Image](https://github.com/user-attachments/assets/be1c66f9-a43d-4e64-865a-4abb50cf0acb)
