### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Jaffoo** [duan602728596/qqtools#180]
大佬，我是后端开发，最近我的web也出现了口袋认证失败的那个问题，我来看大佬你是怎么解决的，但是我前端能力有限看不懂。。。所以我只能来问一下你怎么解决这个问题，我的网易云信初始化代码很简单，如图所示，以我的写法，我改如何改呢？（我没有用electron，就是打包成静态资源，用api访问的）
![image](https://github.com/duan602728596/qqtools/assets/86825947/5c193a9a-c154-4300-ab26-e831bb954961)

**Comment by duan602728596** [comment]
先启动，在浏览器的开发者工具中会看到websocket的通信，会看到返回403。
然后hack NIMSDK和QChatSDK中的`window.WebSocket`，修改send函数。对云信初始化的数据进行修改，达到通过验证的目的。
具体的修改方法可以在代码中找到。

**Comment by Jaffoo** [comment]
我找到了这段代码（一个Qchat，一个NIM的），于是我写入了我的代码中（js文件，在入口index.html直接引入的），在window全局对象添加这两个属。我没用node，所以我直接去替换node_modules中的两个文件中的window.WebSocket成我自定义的window.nimWS，但是还是提示：cmdError: Illegal operation or no permission。是send方法不能照搬您的需要修改吗？还是我解决思路不对？
![image](https://github.com/duan602728596/qqtools/assets/86825947/0e853ba7-9a8f-4292-a796-3efa155ddc15)

**Comment by Jaffoo** [comment]
这个问题解决了，但是直播房间还是进不去，也是403，我依葫芦画瓢，没找到window.websocket相关代码，于是我尝试替换找到websocket的代码尝试替换，没有成功，请问你解决了吗？还是直播的sdk也换了。我用的还是图中的sdk
![image](https://github.com/duan602728596/qqtools/assets/86825947/428456d8-a6f4-423f-9796-6ec189641a04)

**Comment by duan602728596** [comment]
直播的改不了。
