### ISSUE TITLE
请教一下关于打包的问题

### ISSUE THREAD

**Issue by msyy-zj** [duan602728596/qqtools#183]
大佬你好，我尝试拉代码下来自己打包，在编译 unpack.mjs文件时，vscode控制台报错
![image](https://github.com/user-attachments/assets/57d2071c-faf9-4e33-9320-1a2c4088d09d)
目前未找到合适办法解决，请问能帮看看或者提供一些解决思路么

操作步骤
1. cd packages/main     npm run build
2. cd packages/qqtools   npm run build
3. node  run unpack.mjs

操作系统
win11、node-20.16.0 、elenctron-30.0.5 、qqtools-5.6.0

**Comment by duan602728596** [comment]
你这个是从github下载node-nim sdk失败了，你应该翻墙下载。
