### ISSUE TITLE
修改功能不能正常使用 等

### ISSUE THREAD

**Issue by houseyoung** [duan602728596/qqtools#2]
1. 修改功能不能正常使用，点击按钮后，原有信息不能加载到input中。
2. input中不能使用快捷键。
3. 需要一个一键登录所有配置的功能。
感谢~

**Comment by duan602728596** [comment]
第一个是在什么情况下出现的？一般修改之后会直接返回到列表。
第二个是复制粘贴不能用快捷键吗？

**Comment by houseyoung** [comment]
第一个不是编辑之后，是点编辑按钮进入编辑界面，理论上会把原来的数据加载到input里，但是实际上并没有，input是空的。
第二个是的……复制粘贴不能用。
我是挂在windows server 2016服务器上的，我手头只有mac……没法在本地亲测一下。聚聚你那里这两个问题存在吗？

**Comment by duan602728596** [comment]
我这边是腾讯云，windows server 2012的，前两个问题确实是没遇到过

**Comment by houseyoung** [comment]
QAQ，谢谢聚聚了，我再试试吧。那麻烦开发一个一键运行的吧，么么哒。

发自我的 iPhone

**Comment by duan602728596** [comment]
我尽量。。。23333333

**Comment by houseyoung** [comment]
聚聚真甜🤪

发自我的 iPhone

**Comment by duan602728596** [comment]
主要是最近事多。。。。。。

**Comment by 1498774960** [comment]
怎么在播报里加集资人数和当前时间，还有查看链接那个关键词命令怎么改怎么改，打mod 0有点……

**Comment by duan602728596** [comment]
集资人数和当前时间前两天改的时候忘加了......命令在component的callback.js里其实是可以改的

**Comment by 1498774960** [comment]
嗯嗯，毕竟程序员忘东西正常，谢谢大佬！

**Comment by duan602728596** [comment]
@1498774960 不过改命令需要重新编译一下软件，干脆直接下次添加一下命令好了，正好楼上还要加新功能
