### ISSUE TITLE
SDK漏掉消息

### ISSUE THREAD

**Issue by Nothatcold07** [duan602728596/qqtools#24]
大佬，那个SDK版本吞消息的问题是不是无解啊

**Comment by duan602728596** [comment]
吞了什么类型的消息啊？

**Comment by Nothatcold07** [comment]
> 吞了什么类型的消息啊？

跟上次一样 xox房间的发言，语音有时候也会被吞

**Comment by duan602728596** [comment]
那这是sdk的问题了，我也没办法

**Comment by zpr1g** [comment]
我感觉是不是[这儿](https://github.com/duan602728596/qqtools/blob/next/packages/qqtools/src/function/QQ/QQ.ts#L247)的问题？这不是消息数组吗？你只处理了 index 为 0 的。

**Comment by duan602728596** [comment]
index 1的貌似是其他的信息吧




| |
段昊辰
|
|
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

在2020年08月26日 22:42，Yuns 写道：

我感觉是不是这儿的问题？这不是消息数组吗？你只处理了 index 为 0 的。

**Comment by zpr1g** [comment]
那不清楚了，我只是研究 SDK 的时候想到的，还没实操过。我还以为发言频率过快会被合并呢 😄

**Comment by duan602728596** [comment]
不应该，也有可能是那边没处理过来的原因




| |
段昊辰
|
|
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

在2020年08月26日 22:46，Yuns 写道：

那不清楚了，我只是研究 SDK 的时候想到的，还没实操过。我还以为发言频率过快会被合并呢 😄

**Comment by duan602728596** [comment]
吞消息的问题已解决
