### ISSUE TITLE
未知类型的消息弹出

### ISSUE THREAD

**Issue by yakoresya** [duan602728596/qqtools#26]
custom":"{\"messageType\":\"DISABLE_SPEAK\",\"targ

**Comment by duan602728596** [comment]
能不能给我一下完整的信息？现在这个有点少

**Comment by yakoresya** [comment]
：未知信息类型，请联系开发者。
数据：[{"chatroomId":"67322562","idClient":"c9e135b7-025e-4ef1-b61d-0a592b442c19","from":"20190415143030_ezb3ei8g3530b3n","fromNick":"","fromAvatar":"","custom":"{\"messageType\":\"DISABLE_SPEAK\",\"targetId\":\"39846102\",\"sourceId\":\"67322562\"}","fromClientType":"Server","time":1598853274692,"type":"text","text":"","resend":false,"status":"success","flow":"in"}]
时间：2020-08-31 13:54:34
fq

**Comment by duan602728596** [comment]
这个应该是被禁言吧

**Comment by yakoresya** [comment]
对 弹出来群里了  不过是自己看着玩的群不是yyh
