### ISSUE TITLE
桃叭集资

### ISSUE THREAD

**Issue by yakoresya** [duan602728596/qqtools#27]
聚聚的工具很好用
桃叭集资如果有空能加一个排名输出就好了
就是排名第几 前n是谁 这样子

**Comment by duan602728596** [comment]
排行榜输出功能已上线

**Comment by yakoresya** [comment]
谢谢聚聚把pk做出来了，其实我意思是应援会内部的集资排名😂

**Comment by duan602728596** [comment]
导出excel表？还是几个项目的总排名？

**Comment by yakoresya** [comment]
不是，就是说报集资的时候说说这位聚聚排当前这个集资的第几，然后可选输出当前应援会集资排前n的聚聚和集资额：
其实就是桃叭页面里面的那个排行榜，和别的项目无关

**Comment by duan602728596** [comment]
模板内支持输出排行和排行榜

**Comment by yakoresya** [comment]
@hibi 刚刚在【【吴羽霏】专属座位金曲2.0】打赏了7.28元，排行-1位，感谢这位聚聚！
项目地址：https://www.taoba.club/#/pages/idols/detail?id=11503
当前进度：￥29.12 
集资参与人数：3人
项目截止时间：2020-12-01 00:00:00
距离项目截止还有：14天0时47分32秒
排行榜Top5：
1、GNZ48吴羽霏应援会：7.28
2、2468号：7.28
3、金罐加多宝：7.28

--好像是获取的时间差？排行好像有点问题
--以下是格式

@{{ nickname }} 刚刚在【{{ title }}】打赏了{{ money }}元，排行{{rankIndex}}位，感谢这位聚聚！
项目地址：https://www.taoba.club/#/pages/idols/detail?id={{ taobaid }}
当前进度：￥{{ donation }} 
集资参与人数：{{ juser }}人
项目截止时间：{{ expire }}
距离项目截止还有：{{ timedifference }}
排行榜Top5：
{% for item in taobaRankList.slice(0, 4) -%}
{% if loop.index !== 1 -%}{{ '\n' }}{%- endif %}{{ loop.index }}、{{ item.nick }}：{{ item.money }}
{%- endfor %}

--以下是第二次集资

@hibi 刚刚在【【吴羽霏】专属座位金曲2.0】打赏了1.00元，排行0位，感谢这位聚聚！
项目地址：https://www.taoba.club/#/pages/idols/detail?id=11503
当前进度：￥30.12 
集资参与人数：4人
项目截止时间：2020-12-01 00:00:00
距离项目截止还有：14天0时33分48秒
排行榜Top5：
1、hibi：7.28
2、GNZ48吴羽霏应援会：7.28
3、2468号：7.28
4、金罐加多宝：7.28

**Comment by yakoresya** [comment]
好使了，感谢聚聚

**Comment by yakoresya** [comment]
集资命令和群欢迎功能好像都失效了，是不是接收消息的问题？

**Comment by duan602728596** [comment]
> 集资命令和群欢迎功能好像都失效了，是不是接收消息的问题？

命令失效的话重启mirai看看。桃叭的功能和其他功能没有关联。

**Comment by yakoresya** [comment]
--获取时间差好像会造成一点输出问题
--新集资用户排行index是-1

@2468号 刚刚在【【吴羽霏】专属座位金曲2.0】打赏了72.80元，排行5位，感谢这位聚聚！
项目地址：https://www.taoba.club/#/pages/idols/detaail?id=11503
当前进度：￥111.2 
集资参与人数：5人
项目截止时间：2020-12-01 00:00:00
距离项目截止还有：13天23时8分52秒
排行榜Top5：
1、hibi：8.28
2、GNZ48吴羽霏应援会：8.28
3、金罐加多宝：7.28
4、中泰小L：7.28
5、2468号：7.28

--输出格式如下：

@{{ nickname }} 刚刚在【{{ title }}】打赏了{{ money }}元{% if rankIndex !== -1 %}，排行{{rankIndex+1}}位{% endif %}，感谢这位聚聚！
项目地址：https://www.taoba.club/#/pages/idols/detaail?id={{ taobaid }}
当前进度：￥{{ donation }} 
集资参与人数：{{ juser }}人
项目截止时间：{{ expire }}
距离项目截止还有：{{ timedifference }}
排行榜Top5：
{% for item in taobaRankList.slice(0, 5) -%}
{% if loop.index !== 1 -%}{{ '\n' }}{%- endif %}{{ loop.index }}、{{ item.nick }}：{{ item.money }}
{%- endfor %}

**Comment by duan602728596** [comment]
可能是桃叭的订单不同步，获取排行的接口有延迟
