### ISSUE TITLE
最近的一些未知类型

### ISSUE THREAD

**Issue by yakoresya** [duan602728596/qqtools#29]
：未知信息类型，请联系开发者。
数据：[{"chatroomId":"67352339","idClient":"de40f1d4-0c32-4e3d-ab1b-1bf40608b5ff","from":"20190415142512_v451d61n5gdcu2w","fromNick":"","fromAvatar":"","custom":"{\"messageType\":\"TRIP_INFO\",\"tripType\":\"演出\",\"id\":8204,\"title\":\"Class 4 《Waiting 4（肆）》\",\"describe\":\"天天都有小偶像的陪伴\\r\\n轻松快乐度过宅家时光??\\r\\n互动“打CALL”、应援助力、弹幕刷起！\\r\\n宅家生活也精彩！口袋48 等你来约！\",\"jumpPath\":\"trip/detail?id=8204\",\"jumpType\":\"APP_PAGE\"}","fromClientType":"Server","time":1609152795717,"type":"text","text":"","resend":false,"status":"success","flow":"in"}]
时间：2020-12-28 18:53:15

：未知信息类型，请联系开发者。
数据：[{"chatroomId":"67303246","idClient":"3e1e35b7-7de5-4632-84a1-a580c13fd641","from":"20190415141546_8x15ruuhatl9i4s","fromNick":"","fromAvatar":"","custom":"{\"messageType\":\"OPEN_LIVE\",\"id\":548164642306592768,\"coverUrl\":\"/mediasource/live/16086222349390PDSESszI1.jpg\",\"title\":\"《头号新闻》沈梦瑶生日公演\",\"jumpPath\":\"publiclive/detail?id=548164642306592768&starId=407121\",\"startTime\":1608979500000}","fromClientType":"Server","time":1608978914159,"type":"text","text":"","resend":false,"status":"success","flow":"in"}]
时间：2020-12-26 18:35:14

**Comment by duan602728596** [comment]
已发版
