### ISSUE TITLE
自定义命令问题

### ISSUE THREAD

**Issue by Heheda48** [duan602728596/qqtools#3]
原始命令能否删除
在自定义命令中，能否使用关键字，如{{ modianname }}等等（现阶段在文本框无法成功使用关键字）
感谢聚聚提供软件，期待解答，祝生活愉快。

**Comment by duan602728596** [comment]
自定义命令用不了关键字，因为自定义命令不仅仅只是用来发送摩点信息的




| |
段昊辰
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

在2018年10月11日 12:54，Heheda48 写道：

原始命令能否删除
在自定义命令中，能否使用关键字，如{{ modianname }}等等（现阶段在文本框无法成功使用关键字）
感谢聚聚提供软件，期待解答，祝生活愉快。

**Comment by Heheda48** [comment]
那能否修改原始命令名称（比如，改“摩点”命令为“集资”），删除部分冗余命令
其次，自定义命令是否只能发送文本，尚未想到有其余用途
再次感谢聚聚的回答，因为想在实际的应援群中使用，希望能够做到细致入微。

**Comment by duan602728596** [comment]
摩点的话，我可以添加“集资”来触发。
自定义命令本来就是只能发送文本的，发送图片的是cq码，那个是酷q本身的功能。
冗余命令是哪种？口袋48和群欢迎之类的吗？

**Comment by duan602728596** [comment]
也就是说，你不需要在群里查看和输出排行榜吗？

**Comment by Heheda48** [comment]
对的，或者可以设置成管理员触发就更好。
如果方便的话，可以加一下聚聚的qq吗，交流起来比较方便，刚刚尝试加了id上的qq号，如有冒犯请见谅。

**Comment by duan602728596** [comment]
可以啊
