### ISSUE TITLE
未知类型

### ISSUE THREAD

**Issue by yakoresya** [duan602728596/qqtools#30]
：未知信息类型，请联系开发者。
数据：[{"chatroomId":"67352339","idClient":"05dc5b72-47c2-4627-a8c0-27ad2b79bc54","from":"20190415142512_v451d61n5gdcu2w","fromNick":"","fromAvatar":"","custom":"{\"messageType\":\"TRIP_INFO\",\"tripType\":\"演出\",\"id\":8210,\"title\":\"Class 4 《Waiting 4（肆）》\",\"describe\":\"天天都有小偶像的陪伴\\r\\n轻松快乐度过周末时光\\r\\n互动“打CALL”、应援助力、弹幕刷起！\\r\\n宅家生活也精彩！口袋48 等你来约！\\r\\n\",\"jumpPath\":\"trip/detail?id=8210\",\"jumpType\":\"APP_PAGE\"}","fromClientType":"Server","time":1609737803775,"type":"text","text":"","resend":false,"status":"success","flow":"in"}]
时间：2021-01-04 13:23:23

最近好像挺多这种新类型，要不整个默认无视新类型？

**Comment by duan602728596** [comment]
新版本已经添加对未知类型和错误类型的处理
