### ISSUE TITLE
命令疑问及建议

### ISSUE THREAD

**Issue by Ripperso** [duan602728596/qqtools#34]
命令疑问：
请问命令是以什么形式发出的？如log命令，是在群内@机器人，还是以什么形式？

建议：
口袋监听发送消息时，能增加是在哪个房间发送的。如监听多人或者有串门现象时，会出现混淆。

感谢聚聚开源。

**Comment by duan602728596** [comment]
就是在群里直接打命令，如果匹配上了，就会发送消息

**Comment by duan602728596** [comment]
房间消息的话会有昵称啊

**Comment by Ripperso** [comment]
> 房间消息的话会有昵称啊
啊是我配置的原因吗？是一个配置只能监听一个房间吧？
现在显示消息是 发送者昵称+消息+时间，没有显示是在谁的房间发送，比如来自xx的房间。

**Comment by duan602728596** [comment]
奥，懂了，那个确实没有，可以加个配置

**Comment by Ripperso** [comment]
感谢回答 : )

**Comment by duan602728596** [comment]
已发版
