### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by Ripperso** [duan602728596/qqtools#36]
您好，运行script内的unpack进行打包时，提示以下错误：
(node:3040) UnhandledPromiseRejectionWarning: Error: Cannot compute electron version from installed node modules - none of the possible electron modules are installed.  
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246

electron已经全局安装，node版本v12.18.0，运行命令node unpack.js。编译时用的pnpm install，tsc， npm run build。

electron-builder版本切换到v20，可以打包，但是输出程序打开后为空白。

**Comment by duan602728596** [comment]
先安装所有依赖，建议使用npm或者yarn。不需要全局安装electron，暂时不要用11.2以上版本，之前运行错误，我还没确定是否修复。
先编译`packages/qqtools`和`packages/main`，
然后运行`node scripts/unpack`和`ndoe scripts/clean`。

**Comment by Ripperso** [comment]
删除了electron，重新下载了源码，清除了npm缓存，yarn install后编译打包后还是报这个错误。

在packages/qqtools和packages/main里执行了 tsc 和 yarn build。
然后node scripts/unpack。

install的时候有这些warning，有关系吗？
![1](https://user-images.githubusercontent.com/23456134/106985672-d7568080-67a4-11eb-8e3a-5a9c6a13a71e.png)

**Comment by duan602728596** [comment]
没有关系

**Comment by Ripperso** [comment]
已解决，unpack.js - config内需增加配置，electronVersion: '11.1.1'
