### ISSUE TITLE
无法登陆 

### ISSUE THREAD

**Issue by Nothatcold07** [duan602728596/qqtools#37]
电脑自动更新后 出现这个  无法登陆房间 
![X7`_4@6ZD% @Y@P)`L EC4S](https://user-images.githubusercontent.com/66408800/107463883-051f3900-6b9a-11eb-8011-4559c51eb8d7.png)

**Comment by duan602728596** [comment]
插件版本不匹配，降低mirai的版本，换个匹配的版本

**Comment by Nothatcold07** [comment]
> 插件版本不匹配，降低mirai的版本，换个匹配的版本

换了个端口可以了 谢谢大佬  还有就是现在会推送发红包的未知类型信息这个能屏蔽嘛

**Comment by duan602728596** [comment]
屏蔽类型有屏蔽未知类型
