### ISSUE TITLE
特定qq群错误

### ISSUE THREAD

**Issue by TN2win** [duan602728596/qqtools#39]
求问大大
测试了好几个群，有一两个群无论如何都挂不上，为什么呢？

**Comment by duan602728596** [comment]
有什么提示错误？

**Comment by TN2win** [comment]
什么错误都没有提示，就是机器人不工作了，别的群正常工作，群号也没输错

**Comment by duan602728596** [comment]
输入log也没有反应吗

**Comment by TN2win** [comment]
我是直接用4.1.1整包的，要到哪里输入呢

**Comment by duan602728596** [comment]
你检查一下，配置有没有多空格。登陆完毕后，在群里输入`log`，会有消息

**Comment by TN2win** [comment]
配置没多空格，同样群里输入东西，特定群mirai抓不到，别的群的能抓到

**Comment by duan602728596** [comment]
是群，还是临时群？也有可能是群类型不一样吧

**Comment by TN2win** [comment]
是正常的cp应援群，就它一个不行也是很奇妙了

**Comment by duan602728596** [comment]
要么是QQ的问题，要么是QQ群的问题

**Comment by TN2win** [comment]
可是这个qq在别的qq群是没问题的，所以应该是qq群问题
