### ISSUE TITLE
不情之请

### ISSUE THREAD

**Issue by Air433up** [duan602728596/qqtools#40]
请问大佬能打包一份Android版本吗？

**Comment by duan602728596** [comment]
但是electron没有安卓版本啊

**Comment by Air433up** [comment]
> 但是electron没有安卓版本啊

那可以打包一版linux版吗？

**Comment by duan602728596** [comment]
linux可以，但是就是我没linux环境测试，打包完不知道会不会有问题

**Comment by Air433up** [comment]
> linux可以，但是就是我没linux环境测试，打包完不知道会不会有问题

行，我可以帮你测试

**Comment by duan602728596** [comment]
linux的测试版本已经发布了，可以先试一下

**Comment by Air433up** [comment]
> linux的测试版本已经发布了，可以先试一下

好的，非常感谢大佬
