### ISSUE TITLE
口袋房间列表信息更新

### ISSUE THREAD

**Issue by Ripperso** [duan602728596/qqtools#41]
请问该如何获取口袋房间信息列表？

现在的不全。有看到packages\NIMTest\node\index.js文件，不清楚nimToken，token，pa这些参数应该填什么。

**Comment by duan602728596** [comment]
nimToken：48的网易云信sdk的token
token：口袋48的账号对应的云信的account（不是登陆后的token）
pa：口袋48有一些接口需要pa，pa是计算得来的

**Comment by duan602728596** [comment]
[https://github.com/duan602728596/qqtools/commit/bb7957463aa35df81df967825116b79dec21bc97](https://github.com/duan602728596/qqtools/commit/bb7957463aa35df81df967825116b79dec21bc97)新补了四个信息，还缺谁的？

**Comment by Ripperso** [comment]
应该不缺了吧，我记得应该没有关房间的了，感谢！
