### ISSUE TITLE
口袋房间进出显示为乱码

### ISSUE THREAD

**Issue by x12121** [duan602728596/qqtools#44]
口袋房间进出显示为乱码 是我配置出错了吗？
2021-02-20 17:37:20
SNH48-�Ż�� 进入了 GNZ48-л���� 的房间
2021-02-20 17:37:41
SNH48-�Ż�� 离开了 GNZ48-л���� 的房间

**Comment by duan602728596** [comment]
文件编码错误吧，你看看导入的文件是不是utf8的

**Comment by x12121** [comment]
解决了 谢谢
