### ISSUE TITLE
房间登录不进去

### ISSUE THREAD

**Issue by zwtzwx** [duan602728596/qqtools#45]
同样的配置，只是房间 ID 不一样。有一个房间能登录，其他的都登不进去，是不是还有哪些参数需要修改？
![image](https://user-images.githubusercontent.com/23564486/109108836-376e9000-776f-11eb-8b29-11a061688a4c.png)

另外，我远程的服务器是 Linux，没有图形界面。如果我想在远程挂 mcl，本地跑 qqtools 程序，可不可在配置那里添加一个远程 IP 地址的可选项？

谢谢大佬！！

**Comment by duan602728596** [comment]
登不进去，先检查房间是否存在，账号是否关注了房间。

**Comment by duan602728596** [comment]
已发版

**Comment by zwtzwx** [comment]
感谢！！
