### ISSUE TITLE
房间主人进出房间记录

### ISSUE THREAD

**Issue by asjk42** [duan602728596/qqtools#47]
请问是否有办法可以看到房间主人进出自己房间的记录。

**Comment by duan602728596** [comment]
这个目前查不到

**Comment by Ripperso** [comment]
getChatroomMembers方法，guest=false，onlyOnline=true，能查到房间主人进来。

**Comment by william-jw** [comment]
> GetChattomMembers方法，来宾=false，OnlyOnline=true，能查到房间主人进来。

请问这个在电脑上怎么添加呢
