### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by Air433up** [duan602728596/qqtools#51]
“getChatroomMembers方法，guest = false，onlyOnline = true”这个方法似乎是可以查到房间主人进出房间的记录的，大佬有时间可以试一试。

**Comment by duan602728596** [comment]
等我把登陆功能迁移过来之后的吧

**Comment by Air433up** [comment]
嗯嗯，好的，大佬辛苦了

**Comment by william-jw** [comment]
期待

**Comment by Air433up** [comment]
> 等我把登陆功能迁移过来之后的吧

大佬，有试试这个方法可以实现查到房间主人进出房间的记录吗？
