### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by lanfeng-shui** [duan602728596/qqtools#52]
求助，房间存在且已经关注该房间 ，登录的时候提示连接断开，请问如何解决呢？

**Comment by duan602728596** [comment]
account正确填写了吗?

**Comment by lanfeng-shui** [comment]
acccount是按照你的方法去找的 我不是很懂这些 就按照教程一步步填的
![屏幕截图(5)](https://user-images.githubusercontent.com/81756923/113314381-da05ca00-933e-11eb-8044-226b9ff3c917.png)
![屏幕截图(3)](https://user-images.githubusercontent.com/81756923/113314391-dc682400-933e-11eb-9bd7-7c2080349e5e.png)
![屏幕截图(4)](https://user-images.githubusercontent.com/81756923/113314401-df631480-933e-11eb-9915-3513b59c9359.png)

**Comment by lanfeng-shui** [comment]
关闭口袋监听后能成功登陆 不知道监听那里哪个错了

**Comment by duan602728596** [comment]
口袋48的是account，不是appuid。
mirai的mirai-http-api要配置，把websocket打开。
然后为了安全，我把你的图片删了。

**Comment by lanfeng-shui** [comment]
谢谢，按照要求更改之后成功登陆，感恩。
