### ISSUE TITLE
提问和反馈

### ISSUE THREAD

**Issue by Kingzoey** [duan602728596/qqtools#53]
想请问OWhat链接可以监控吗？还有一个小问题就是我在本地电脑上运行，今天测试发现有存在吞文字消息的情况，大约十条消息里有两条没有发送出来，想请教一下大佬

**Comment by duan602728596** [comment]
现在因为常用的是桃叭，所以没有集成owhat。吞文字的话，你的mirai的版本和mirai-http-api的版本都是哪个版本

**Comment by Kingzoey** [comment]
> 现在因为常用的是桃叭，所以没有集成owhat。吞文字的话，你的mirai的版本和mirai-http-api的版本都是哪个版本

哦哦原来如此。因为我们家貌似使用owhat多一些，所以我自己希望可以统计owhat的链接。mirai的话因为我是使用别人集成好http-api等插件的mcl-1.0.5包进行配置使用的。刚才也试着去找了下版本，因为我对mirai还不熟悉好像没能找到，我手动更新了http-api至1.10.0，目前的mirai-core和mirai-console在config文件里显示的版本是2.4.0

**Comment by duan602728596** [comment]
owhat你可以找Lgyzero或者GG的用。吞消息是吞了哪种消息？我不确定是不是mirai版本的原因，或者是httpapi插件的原因，你可以重启试试

**Comment by Kingzoey** [comment]
> owhat你可以找Lgyzero或者GG的用。吞消息是吞了哪种消息？我不确定是不是mirai版本的原因，或者是httpapi插件的原因，你可以重启试试

就是单纯的文字消息被吞了，发了大概几条比较短的文字消息，几个字的那种，几条中被吞了一条。我刚才更新后重启了准备看看还会不会出现这种情况

**Comment by duan602728596** [comment]
消息的时间间隔是多少？

**Comment by Kingzoey** [comment]
下面上面的是应援会群机器人记录，下面的是我这边的记录，14:51:49的那条“好吃又健康”没发送出来。

口袋房间 更新:
SNH48-宋昕冉:
[图片]
2021-04-03 14:50:27

口袋房间 更新:
SNH48-宋昕冉:
[emoji]
2021-04-03 14:50:56

口袋房间 更新:
SNH48-宋昕冉:
好吃又健康
2021-04-03 14:51:49

Odyssey 14:52:47
口袋房间 更新:
SNH48-宋昕冉:
可比高粱饴好吃多了
2021-04-03 14:52:46
------------------------------

SNH48-宋昕冉 发送了一张图片：
时间：2021-04-03 14:50:27
房间：SNH48-宋昕冉 的口袋房间

SNH48-宋昕冉：[emoji]
时间：2021-04-03 14:50:56
房间：SNH48-宋昕冉 的口袋房间

SNH48-宋昕冉：可比高粱饴好吃多了
时间：2021-04-03 14:52:46
房间：SNH48-宋昕冉 的口袋房间

**Comment by duan602728596** [comment]
你用的开保存口袋日志了吗？没有的话下个最新的，可以保存日志，对比一下

**Comment by Kingzoey** [comment]
后面也吞了一个消息，15:00:41 15:03:50 15:04:43  中间15:03:50的这条也没发出来。我看了日志里也没有没发出来的消息，我这边自己再看看有没有出现这种情况了，谢谢大佬啦

**Comment by duan602728596** [comment]
日志里没有的话，那可能就是sdk的问题了

**Comment by Kingzoey** [comment]
明白。我这边的欢迎功能好像也不太好使，<%= qqtools:At %> 在邀请进群或者搜索群号进群的时候都没有@和发送消息

**Comment by duan602728596** [comment]
欢迎你是怎么配置的？我这边一直都是好使的

**Comment by Kingzoey** [comment]
就是在群欢迎功能那里开启，然后发送消息是下面这一行

<%= qqtools:At %>欢迎

我也不知道怎么不行……

**Comment by Kingzoey** [comment]
不过消息接收现在还是比较稳定的，刚才几十条好像没有被吞的

**Comment by duan602728596** [comment]
应该好使啊...，我也这么配置的

**Comment by Kingzoey** [comment]
> 应该好使啊...，我也这么配置的

也可能是我这样本太少了，就我跟我小号拉来拉去的😂 反正我这就是自己用个乐呵，辛苦大佬下午的解答了！

**Comment by duan602728596** [comment]
等我晚上看看，应该是没问题的

**Comment by Kingzoey** [comment]
辛苦辛苦~

**Comment by duan602728596** [comment]
吞消息的问题已解决
