### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by shangusl** [duan602728596/qqtools#54]
会出现吞消息的情况，这种情况一般出现在平常比较热闹的房间里；还有就是今天出现了一个这样的情况
![1](https://user-images.githubusercontent.com/81770226/113475484-93cc7a00-94a8-11eb-90da-046b00f87ed4.png)

**Comment by duan602728596** [comment]
吞消息的话，我会考虑一下解决方法，让消息队列发送。你这个的是未知类型，你可以使用屏蔽未知消息类型来处理。日志记录一下倒是没什么

**Comment by duan602728596** [comment]
你这个信息以文字给我发过来吧。我对这个信息进行一下处理

**Comment by shangusl** [comment]
> 你这个信息以文字给我发过来吧。我对这个信息进行一下处理

好的
SNH48-孙芮：未知信息类型，请联系开发者。
数据：[{"chatroomId":"67322480","idClient":"2f863fa7-c794-42cd-85cb-4f2395a682fd","from":"20190415141602_xq720d9xxuf9c9i","fromNick":"","fromAvatar":"","fromCustom":"","userUpdateTime":1617442793138,"custom":"{\"replyName\":\"美女廖???\",\"messageType\":\"GIFTREPLY\",\"bubbleId\":\"338785331586015250\",\"replyText\":\"送了1个应援棒-SII\",\"roomId\":\"67322480\",\"sourceId\":\"67322480\",\"module\":\"session\",\"config\":{\"build\":\"210202\",\"phoneName\":\"unknow\",\"version\":\"6.1.1\",\"mobileOperators\":\"中国联通\",\"phoneSystemVersion\":\"14.4.2\"},\"sessionRole\":2,\"text\":\"他说发两个 不然怕别人说他太小气\",\"fromApp\":\"201811\",\"replyMessageId\":\"633bca7e-bf7b-452f-9ce1-17f8ab5c7eef\",\"giftInfo\":{\"fullPicPath\":\"https:\\/\\/source.48.cn\\/mediasource\\/gift\\/0dc31ec3-e964-435b-92f2-65bde3ef6c0d.png\",\"picPath\":\"\\/mediasource\\/gift\\/0dc31ec3-e964-435b-92f2-65bde3ef6c0d.png\",\"click\":true,\"isVote\":false,\"special\":false,\"giftNum\":1,\"giftId\":\"266592587658117120\",\"giftName\":\"应援棒-SII\"},\"user\":{\"roleId\":3,\"vip\":false,\"nickName\":\"SNH48-孙芮\",\"teamLogo\":\"\\/mediasource\\/teamLogo2\\/all\\/snh48_s2.png\",\"userId\":8,\"avatar\":\"\\/20191210\\/1575973073930ioN62d72R8.jpg\"},\"keyWordStatus\":false}","fromClientType":"iOS","time":1617443272818,"type":"text","text":"","resend":false,"status":"success","flow":"in"},{"chatroomId":"67322480","idClient":"0ecb76784f464fbd9a9de036103e65df","from":"20200626151328_a6whaehtdf3poei","fromNick":"","fromAvatar":"","fromCustom":"","userUpdateTime":1617443135129,"custom":"{\"sourceId\":\"67322480\",\"keyWordStatus\":false,\"sessionRole\":0,\"messageType\":\"TEXT\",\"fromApp\":\"201811\",\"module\":\"session\",\"bubbleId\":\"0\",\"text\":\"哇\",\"user\":{\"birthday\":\"\",\"imPwd\":\"\",\"gender\":0,\"sessionRole\":0,\"city\":\"\",\"badgeCount\":0,\"deviceId\":\"\",\"nickname\":\"\",\"isOwener\":false,\"exp\":0,\"vip\":false,\"teamLogo\":\"\",\"level\":3,\"nickName\":\"Sarie\",\"roleId\":1,\"Verification\":false,\"bgImg\":\"\",\"avatar\":\"\\/20200813\\/1597312231520a9Uwc8h5x5.jpeg\",\"expArr\":[],\"userId\":9108979749,\"friends\":0,\"token\":\"\",\"badge\":[],\"followers\":0,\"isStar\":false,\"money\":0,\"imUserId\":\"\",\"roleName\":\"\",\"userRole\":0,\"support\":0,\"card\":0,\"mangerName\":\"\"},\"config\":{\"mobileOperators\":\"未知\",\"phoneSystemVersion\":\"10\",\"build\":\"181022\",\"version\":\"6.1.0\",\"phoneName\":\"PBEM00\"},\"roomId\":\"67322480\"}","fromClientType":"Android","time":1617443273131,"type":"text","text":"","resend":false,"status":"success","flow":"in"}]
时间：2021-04-03 17:47:52
房间：SNH48-孙芮 的口袋房间

**Comment by shangusl** [comment]
麻烦大佬了，谢谢解答
