### ISSUE TITLE
内置的mirai登录总是失败

### ISSUE THREAD

**Issue by onlyzqy** [duan602728596/qqtools#56]
用内置的mirai一直显示登录失败，请问一下该怎么设置呢？

**Comment by duan602728596** [comment]
下载mirai-console-{version}-all.jar、mirai-console-terminal-{version}-all.jar、mirai-core-all-{version}-all.jar这三个jar文件，放到一个目录内，下载mirai-api-http插件。

启动前需要配置java文件位置，配置jar文件夹的位置。

**Comment by KOUymA** [comment]
想问下 java文件指的是哪一个文件？
