### ISSUE TITLE
消息转发问题

### ISSUE THREAD

**Issue by Air433up** [duan602728596/qqtools#58]
大佬，近期出现了过一段时间后，大概5个小时左右，QQ群就会接收不到消息，但mirai console的窗口中有的问题。
mirai版本2.6.2M
mirai-api-http版本1.11.0
Java环境：openjdk 11
qqtools版本4.4.0
服务器环境：winserver2012 64位中文版

**Comment by lanfeng-shui** [comment]
我这边也是这样

**Comment by Air433up** [comment]
@lanfeng-shui 猜测可能是mirai-api-http更新了导致的，等大佬出来解决了

**Comment by duan602728596** [comment]
接收不到消息时qq是否在线

**Comment by Air433up** [comment]
在线的，发现了是mirai的问题，用2.4.0版就没问题，用2.6.2M就会出现

**Comment by duan602728596** [comment]
还是用正式版本吧，测试版本还是不太稳定

**Comment by Air433up** [comment]
嗯嗯，好的，大佬辛苦了

**Comment by lanfeng-shui** [comment]
我这边mirai用2.4也是不行的，所以可能还是跟mirai-api-http版本有关
mirai版本2.4
mirai-api-http版本1.9.8
Java环境：openjdk 11
qqtools版本4.4.0
服务器环境：winserver2019 64位中文版

**Comment by Air433up** [comment]
@lanfeng-shui 你可以拿最新的api试试

**Comment by lanfeng-shui** [comment]
感谢 中午换成1.11.0了 到目前为止没有出现问题
