### ISSUE TITLE
新添加的QQ群，必须重启软件机器人才可以发送信息吗

### ISSUE THREAD

**Issue by LUDA-LLX** [duan602728596/qqtools#59]

**Comment by duan602728596** [comment]
你是怎么重启的？

**Comment by LUDA-LLX** [comment]
我就是之前运行的好好的，然后后面添加的配置改了一下群号 发现机器人不会发送消息了，我就把文件删了重新下了一遍 添加后就又能发送了

**Comment by duan602728596** [comment]
你在配置修改群号不影响已经运行的qq啊。
你修改完把正在运行的关了再重新登陆就好了

**Comment by LUDA-LLX** [comment]
我遇到的情况是，程序运行时 我添加了一个新加入的QQ群，反复登陆也是成功的，老群可以收到消息，但是新加入的那个群（QQ也是新加入的那个群)是不会发送信息的，是不是要重新登陆QQ 或者重启软件才可以？感谢大佬百忙之中回复我这种小问题！

**Comment by duan602728596** [comment]
你试试在两个群里输入`log`，看看是否触发命令。

**Comment by LUDA-LLX** [comment]
log怎么用啊😂命令那里我没搞懂

**Comment by duan602728596** [comment]
在群里输入`log`，然后发送

**Comment by LUDA-LLX** [comment]
我在机器人正常运行的情况下发log. 也没什么反应诶

**Comment by duan602728596** [comment]
其他的触发命令也不好使吗？你现在的mirai版本和插件版本是哪个版本？

**Comment by LUDA-LLX** [comment]
我没注意版本，我回去看看 如果不是最新版本的就尝试最新版本的是吧？感谢解答

**Comment by Air433up** [comment]
@LUDA-LLX mirai-api-http的配置文件中enableWebsocket的值要改为true，才能使用命令
