### ISSUE TITLE
账号登陆失败

### ISSUE THREAD

**Issue by eckhardliu** [duan602728596/qqtools#60]
mirai登录那里账号登陆的时候总说上网环境异常 换了热点wifi跟有线网络都不行 怎么办啊?

**Comment by duan602728596** [comment]
是mirai可以启动，但是软件控制台里显示的“上网环境异常 ”吗？
如果是小号，建议挂一段时间。或者换一个账号试试。
最好来个截图。

**Comment by eckhardliu** [comment]
![image](https://user-images.githubusercontent.com/65560041/114813597-0f9dbf00-9de5-11eb-9cf6-22cef98160bd.png)
划完验证码 就跳这个出来

**Comment by duan602728596** [comment]
你是不是滑动验证码填写错了？

**Comment by eckhardliu** [comment]
![image](https://user-images.githubusercontent.com/65560041/114813883-95ba0580-9de5-11eb-8b4e-fdd902622380.png)
没错啊

**Comment by duan602728596** [comment]
果然错了

**Comment by eckhardliu** [comment]
呃....?

**Comment by duan602728596** [comment]
首先你需要在浏览器打开给你的滑动验证地址，然后打开开发者控制台，切换到Network。
然后滑动完成后找到name为cap_union_new_verify的相应（response），里面的ticket填写到这里。

**Comment by eckhardliu** [comment]
嗷 谢谢大哥 知道了
