### ISSUE TITLE
消息推送问题

### ISSUE THREAD

**Issue by shangusl** [duan602728596/qqtools#61]
大佬，4.4.2版本可能存在着消息推送的问题，通常挂几个小时之后消息就不会正常推送了，但日志内有消息记录。
一开始是觉得mirai版本的问题，所以退回到了2.4的版本，但情况依然发生。之后也试了2.6的版本，但情况依然存在。
mirai-api-http的版本是1.11.0。
4.4.1版本下推送无异常。

**Comment by duan602728596** [comment]
打开控制台，然后再出现这种情况，检查一下是否有400错误

**Comment by shangusl** [comment]
> 打开控制台，然后再出现这种情况，检查一下是否有400错误

这两天没有出现这种问题了，可能跟mirai的版本更新到2.6.1的情况有关，至于之前有没有出现过400的错误我不确定

**Comment by duan602728596** [comment]
你可以试试最新发版的，可能是由于错误导致函数没执行完，占用了发送队列导致的

**Comment by shangusl** [comment]
> 你可以试试最新发版的，可能是由于错误导致函数没执行完，占用了发送队列导致的

好的，谢谢大佬解答啦

**Comment by shangusl** [comment]
> 你可以试试最新发版的，可能是由于错误导致函数没执行完，占用了发送队列导致的

4.4.3的版本挂了几个小时之后消息也不推送了，重登之后在控制台能看到消息，但是QQ群里面没有推送

**Comment by shangusl** [comment]
排查了一下，应该是mirai版本的问题。
