### ISSUE TITLE
进入房间问题

### ISSUE THREAD

**Issue by solskenl** [duan602728596/qqtools#62]
使用内置mirai登陆QQ成功后，配置登陆信息中的authkey和端口号在哪看 因为我配置完点击登录旁边会有一个小圈，没有反应，没有显示成功加入房间也没有报错。麻烦大佬解答一下我这个问问，谢谢大佬了。

**Comment by duan602728596** [comment]
https://github.com/project-mirai/mirai-api-http#settingyml%E6%A8%A1%E6%9D%BF
