### ISSUE TITLE
连接断开问题

### ISSUE THREAD

**Issue by KOUymA** [duan602728596/qqtools#65]
大佬求助 
mirai登陆成功 关闭口袋监听 账号成功登录
![image](https://user-images.githubusercontent.com/72074577/118502040-e6fa4380-b75b-11eb-881c-7a76cbc49d93.png)
但是 开启口袋监听
![image](https://user-images.githubusercontent.com/72074577/118501659-8bc85100-b75b-11eb-8519-484b35609dcb.png)
显示连接断开 
账号account填的是snh48开头的
mirai的websocket也打开了

**Comment by duan602728596** [comment]
如果你的账号是瓜号的话，account可能是纯数字

**Comment by KOUymA** [comment]
打开console 说的是这个？
![image](https://user-images.githubusercontent.com/72074577/118504386-0a25f280-b75e-11eb-9419-7c4fa0968475.png)

**Comment by KOUymA** [comment]
感谢大佬 确实用纯数字的就好了
