### ISSUE TITLE
关于setting.yml文件的疑问

### ISSUE THREAD

**Issue by xfxyszd** [duan602728596/qqtools#66]
请问一下，为什么我生成的setting.yml文件，和说明手册里的文件内容代码完全不同，没有端口号 和 authkey …，后来我复制粘贴了说明手册的yml里代码到文件里，也修改了端口号和authkey，但是群机器人还是不能监听，我测试一下，监听微博买也不行，哪里出现了问题。

**Comment by duan602728596** [comment]
用v1版本

**Comment by xfxyszd** [comment]
> 用v1版本

可以说的详细点吗？听不懂什么是v1版本😂

**Comment by duan602728596** [comment]
mirai-api-http

**Comment by xfxyszd** [comment]
> mirai-api-http用v1的版本

![2951621486051_ pic_hd](https://user-images.githubusercontent.com/75834774/118920792-a708ab80-b969-11eb-8773-00862045eaf7.jpg)
换了v1版本的，yml文件也出现端口号和authkey，但是我还是无法使用监听，我拿微博号测试了监听功能，到底是为什么呢

**Comment by duan602728596** [comment]
微博的id对了吗？

**Comment by xfxyszd** [comment]
![2991621486491_ pic](https://user-images.githubusercontent.com/75834774/118921640-1763fc80-b96b-11eb-9cab-38a508e783d3.jpg)
应该是对的 
另外还有就是我找不account信息
![3001621487085_ pic_hd](https://user-images.githubusercontent.com/75834774/118922083-f4861800-b96b-11eb-9d73-a379efd84e0f.jpg)

**Comment by duan602728596** [comment]
试试用自定义命令，看看是否触发
account需要登陆

**Comment by xfxyszd** [comment]
> 请使用自定义命令，看看是否触发
> 帐户需要登陆
弄不来 😟请问自定义具体怎么操作 😂 感觉qq绑定的机器人是死的 虽然登入了 但是啥也干不了

**Comment by duan602728596** [comment]
你照着说明书操作，然后启动后在群里打`log`命令，看看有没有消息。

**Comment by xfxyszd** [comment]
> 你照着说明书操作，然后启动后在群里打`log`命令，看看有没有消息。

![image](https://user-images.githubusercontent.com/75834774/118959978-64f55f00-b995-11eb-8000-38cc20f5bae8.png)
这又是什么意思

**Comment by duan602728596** [comment]
你如果mirai-api-http插件配置对了，重启mirai。
否则就照着mirai和mirai-api-http的文档配置。
