### ISSUE TITLE
连接断开

### ISSUE THREAD

**Issue by Nothatcold07** [duan602728596/qqtools#68]
今天下午发现有的口袋房间发言没有推送
就去重启了下qqtools 
再登录的时候显示连接断开

**Comment by xfxyszd** [comment]
我也，本来登上去了，但是不推送我就退出，重新登入就说连接断开
![image](https://user-images.githubusercontent.com/75834774/118968652-c1a94780-b99e-11eb-9ba9-ac5feeadb9ea.png)

**Comment by shiningPrince1003** [comment]
官网直播认证改了 不再使用setcookie；
挂qqtools的口袋48账号被nim封禁，错误码为422；
被封账号可以正常登陆口袋48；
被封禁的口袋48账号，在官网直播页登陆时，cookie里只有browser 和phpsessid两个值 未被封号的另外还有一个username值

**Comment by duan602728596** [comment]
目前没法获取account了，但是有的account还可以正常使用，我的account虽然没挂口袋，但也被禁言了。
这几天去看ckg，等回来再处理看看。

**Comment by duan602728596** [comment]
已经找到新的认证方法了，最近会更新一下。
