### ISSUE TITLE
使用qqtools登录失败

### ISSUE THREAD

**Issue by KOUymA** [duan602728596/qqtools#72]

**Comment by KOUymA** [comment]
jdk的问题

**Comment by duan602728596** [comment]
先下载好对应版本的jdk，最好是openjdk，mirai相关的要下载正式版，mirai-api-http下载v1版本的。这种都需要你自己处理好。

**Comment by KOUymA** [comment]
> 先下载好对应版本的jdk，最好是openjdk，mirai相关的要下载正式版，mirai-api-http下载v1版本的。这种都需要你自己处理好。
谢谢大佬
后来发现是jar包下错了 重新下了就解决了 不过关闭不了issue
话说q号太容易被封 大佬有什么办法吗（已经手机+pc挂了一个星期

**Comment by duan602728596** [comment]
接着挂吧，顺便把设备锁啥的开启了
