### ISSUE TITLE
消息log看不到删除了哪一条发言

### ISSUE THREAD

**Issue by shiningPrince1003** [duan602728596/qqtools#73]
当前版本（4.5）的消息文件 XXX.log 中，房间消息记录没有消息ID，删除信息记录没有消息内容，如果可以记录消息同时记录消息ID的话，就可以看到是删除了具体哪一条消息

**Comment by duan602728596** [comment]
其实删除消息这个，是删除自己的发言和房间内别人的发言都会触发的
