### ISSUE TITLE
启动mirai出错

### ISSUE THREAD

**Issue by TN2win** [duan602728596/qqtools#74]
错误: 无法初始化主类 net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader
原因: java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope
![image](https://user-images.githubusercontent.com/78290805/121524776-39acdf80-ca2a-11eb-80f7-4147ed13bdd9.png)
![image](https://user-images.githubusercontent.com/78290805/121524860-50533680-ca2a-11eb-9ca0-78940ae51148.png)
![image](https://user-images.githubusercontent.com/78290805/121524878-56491780-ca2a-11eb-9833-7fbbca53e1b9.png)

**Comment by duan602728596** [comment]
测试没有问题，可以正常启动。
mirai不建议使用测试版本。
java建议使用openjdk。
mirai-api-http检查和当前版本的mirai是否兼容。
