### ISSUE TITLE
投票不显示房间主人

### ISSUE THREAD

**Issue by TN2win** [duan602728596/qqtools#77]
![image](https://user-images.githubusercontent.com/78290805/122049568-29737680-ce15-11eb-94db-09c52d7d33c8.png)

**Comment by duan602728596** [comment]
需要配置“发送时带上房间信息”，且要导入房间信息

**Comment by TN2win** [comment]
已经是配置了的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月15日(星期二) 晚上8:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [duan602728596/qqtools] 投票不显示房间主人 (#77)





 
需要配置“发送时带上房间信息”，且要导入房间信息

**Comment by duan602728596** [comment]
房间信息里有没有成员名？

**Comment by TN2win** [comment]
有，发送消息其他的一切正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月15日(星期二) 晚上8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [duan602728596/qqtools] 投票不显示房间主人 (#77)





 
房间信息里有没有成员名？

**Comment by duan602728596** [comment]
给我截个完整的记录吧，带房间的和不带房间的

**Comment by TN2win** [comment]
![image](https://user-images.githubusercontent.com/78290805/122053949-ce904e00-ce19-11eb-8d05-aa4dd5d9b4be.png)
设置是这样的，其他人都不带房间
![image](https://user-images.githubusercontent.com/78290805/122054330-28911380-ce1a-11eb-9806-25ed18535bc8.png)
只有ddd带房间了
![image](https://user-images.githubusercontent.com/78290805/122054492-4eb6b380-ce1a-11eb-9538-6ca078a2dc1a.png)
js里面是有名字的

**Comment by TN2win** [comment]
![image](https://user-images.githubusercontent.com/78290805/122054710-832a6f80-ce1a-11eb-90cb-e4e50b8f72b9.png)
mirai里面也不显示

**Comment by duan602728596** [comment]
我看看是不是account变了

**Comment by TN2win** [comment]
我把进出房间提示打开就显示名称了。
（顺便问一下，大佬什么时候添加直播票数啊，现在还看不了直播票数统计不准确）

**Comment by TN2win** [comment]
但是单独只打开显示房间信息就不行

**Comment by duan602728596** [comment]
找到问题了

**Comment by duan602728596** [comment]
已发版
