### ISSUE TITLE
RequestError: connect ECONNREFUSED

### ISSUE THREAD

**Issue by Hz007** [duan602728596/qqtools#78]
使用qqtools启动mirai
在mirai登陆页面登陆显示成功，监听配置中端口号及authKey均与mirai-api-http的setting一致，但是在帐号登陆时出现无法登陆的情况，打开mirai控制台看见的报错信息为RequestError: connect ECONNREFUSED 127.0.0.1:8080
 mirai-api-http版本为v1.11.0

**Comment by duan602728596** [comment]
1、检查java SDK版本
2、检查mirai-api-http和mirai版本是否兼容
3、检查端口是否被占用
4、检查mirai-api-http是否开启websocket功能
5、可以先从命令行启动mirai
