### ISSUE TITLE
房间只能登录一个&投票信息的bug

### ISSUE THREAD

**Issue by 0xwhy** [duan602728596/qqtools#79]
一个应用里房间只能进一次。如果有两个群需要抓同一个房间，只有第一个登陆的号会显示进入房间成功，第二个号不会显示进入成功
现在我开了两个应用，每个应用挂不同的号(抓同一个房间)。但投票信息显示会错误（”xxx：投出了x票“这个文字消息是正常的，但图片不对，票的图片有时候会变成应援棒，玫瑰花，秋天的奶茶等）

**Comment by duan602728596** [comment]
同一个房间共用一个NimChatroomSocket实例，只连接一次，所以只有第一次连接会提示成功。
投票信息已经修复，下载最新版本。
