### ISSUE TITLE
mirai登录正常，但挂口袋的时候出现中断

### ISSUE THREAD

**Issue by TN2win** [duan602728596/qqtools#81]
![image](https://user-images.githubusercontent.com/78290805/122410015-2a8fd980-cfb6-11eb-81f2-b5bc6436250b.png)

**Comment by TN2win** [comment]
![image](https://user-images.githubusercontent.com/78290805/122411722-8dce3b80-cfb7-11eb-95ee-3cf67cc033e0.png)

**Comment by duan602728596** [comment]
看看mirai-api-http是否兼容当前版本的mirai，最好不要使用测试版本

**Comment by TN2win** [comment]
mirai-api-http采用v1.11.0正式版
content里采用过2.6.6 2.5.1 2.4.1都不行

**Comment by duan602728596** [comment]
websocket开了么

**Comment by duan602728596** [comment]
#83
