### ISSUE TITLE
mirai升级后机器人无法登陆账号

### ISSUE THREAD

**Issue by 0xwhy** [duan602728596/qqtools#82]
mirai自动升级后，机器人无法登陆账号。登陆按钮在一直转圈，也没有提示消息
iTXTech Mirai Console Loader version 1.0.5-9b6cf6d(这个应该是版本信息吧)

**Comment by duan602728596** [comment]
看这里解决问题 #83

**Comment by 0xwhy** [comment]
谢谢大哥指点，把mirai-console换成老版本就可以用了
