### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by Air433up** [duan602728596/qqtools#84]
大佬，编译进行到打包软件时报错如下，经百度仍未解决
![image](https://user-images.githubusercontent.com/60246381/123818700-c8c35e00-d92b-11eb-8f79-89f6a7097ff0.png)

**Comment by duan602728596** [comment]
如图所示，非mac系统不支持编译mac版本，把脚本中的mac相关的代码注释掉就好了

**Comment by Air433up** [comment]
> 提示所示，非mac系统不支持编译mac版本，把脚本中的mac相关的代码注释掉就好了

刚刚注释完编译又提示get问题，如图
![image](https://user-images.githubusercontent.com/60246381/123887983-19b37080-d985-11eb-8f02-854944e748e4.png)

**Comment by Air433up** [comment]
解决了，感谢
