### ISSUE TITLE
夜蝶跟皇冠会被判定为总选投票

### ISSUE THREAD

**Issue by chenzibin2019** [duan602728596/qqtools#89]

**Comment by duan602728596** [comment]
最好提供截图或软件版本。

**Comment by duan602728596** [comment]
[v4.6.3](https://github.com/duan602728596/qqtools/releases/tag/v4.6.3)
#79

**Comment by chenzibin2019** [comment]
您好，当前运行版本为4.6.4 问题截图：

[cid:952A9E2A-A64E-4C4C-A013-A841E2600338]

On Jul 20, 2021, at 9:35 PM, B.B.K.K.B.K.K（段昊辰） ***@***.******@***.***>> wrote:



Closed #89<https://github.com/duan602728596/qqtools/issues/89>.

**Comment by duan602728596** [comment]
已修复
