### ISSUE TITLE
口袋48房间监：非法授权。

### ISSUE THREAD

**Issue by eatgreenbeam** [duan602728596/qqtools#9]
连接时有这个提示  无法使用

**Comment by eatgreenbeam** [comment]
> 连接时有这个提示 无法使用

**Comment by duan602728596** [comment]
账号一次只能登陆一个设备




| |
段昊辰
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

在2019年06月02日 16:24，eatgreenbeam 写道：

连接时有这个提示 无法使用

**Comment by Francis0546** [comment]
我也显示这个问题。
口袋48房间监：非法授权
“账号一次只能登陆一个设备”是指口袋账号，还是QQ账号？

**Comment by duan602728596** [comment]
@Francis0546 口袋账号。无法使用是偶尔还是经常？你的账号是手机号还是其他账号？

**Comment by Francis0546** [comment]
刚开始使用这个工具，监听房间功能还没有测试成功过（其他功能都可以）。口袋账号是手机号，在手机及其他设备上都退出登录了，也未能测试成功。

**Comment by Francis0546** [comment]
问题解决了，感谢
