### ISSUE TITLE
直播艾特全体功能

### ISSUE THREAD

**Issue by LUDA-LLX** [duan602728596/qqtools#92]
因为一个普通QQ群只能艾特全体10次，像直播多的xox多播几次就无了，可不可以设置触发后发送信息，不艾特全体

**Comment by duan602728596** [comment]
你把at去掉就好了啊，目前我也获取不到at次数

**Comment by LUDA-LLX** [comment]
能不能告知去掉哪里的at没找到

**Comment by LUDA-LLX** [comment]
明白了，取消艾特全体就好了，解决，
那如果可以的话可以自己设置艾特单人吗 怎么改呀

**Comment by LUDA-LLX** [comment]
明白了，谢谢

**Comment by duan602728596** [comment]
有直播时at全体那个选项
