### ISSUE TITLE
mirai有bug，更新后qq机器人无法使用新的mirai console

### ISSUE THREAD

**Issue by 0xwhy** [duan602728596/qqtools#97]
## 错误报告

mirai今天出现了无法发送图片的bug https://github.com/mamoe/mirai/issues/1536
更新了2.7.1-dev-1后解决，但qq机器人无法使用2.7.1-dev-1，只能使用2.6.0以前的版本，无法发送图片

## 复现步骤

console降级到2.6.0(但23:30左右发现好像连消息都发不了)
## 预期行为

能正常使用

## 使用环境

- 操作系统：win10
- 软件版本：4.7.4

**Comment by duan602728596** [comment]
经测试mirai@2.7.1-dev-1 + mirai-api-http@2.3.0可以正常使用，并发送网络和本地图片。请检查插件的版本是否匹配当前的mirai版本。
![48df4474-2597-487b-ba11-dc719711ae57](https://user-images.githubusercontent.com/17332657/132809338-54eb3027-69ba-4adc-a650-6b8b8d059632.jpg)

**Comment by 0xwhy** [comment]
![image](https://user-images.githubusercontent.com/85991792/132810260-b92f7df7-5df1-47ad-ad17-e3731b741b9e.
你的文档上面写的只能用V1版本
![image](https://user-images.githubusercontent.com/85991792/132810470-91b02534-8b3c-44f4-a91b-9738658bb6f1.png)
这样会显示“登陆失败：获取session失败。”

**Comment by duan602728596** [comment]
早就已经支持v2版本，兼容v1版本了。我更新一下文档。
