### ISSUE TITLE
大大  最近用这个机器人好像抓不到房间里的图片信息了  其他文字 上下线等都正常 是小号被qq系统屏蔽了还是软件的缘故

### ISSUE THREAD

**Issue by longgu2021** [duan602728596/qqtools#98]
## 使用环境

- 操作系统：
- 软件版本：

**Comment by duan602728596** [comment]
https://github.com/mamoe/mirai/issues/1536
https://github.com/duan602728596/qqtools/issues/97
用自定义命令测试一下能不能发图片，不能发的话更新一下mirai和mirai-api-http的版本。

**Comment by longgu2021** [comment]
https://github.com/mamoe/mirai/issues/1536   好像问题是出在了这里 好像2.7版本就能用了

**Comment by duan602728596** [comment]
> [mamoe/mirai#1536](https://github.com/mamoe/mirai/issues/1536) 好像问题是出在了这里 好像2.7版本就能用了

那就是同一个问题，那就已经解决了

**Comment by eckhardliu** [comment]
我更了2.7.1跟2.3.0 好像还是不行诶😢

**Comment by duan602728596** [comment]
> 我更了2.7.1跟2.3.0 好像还是不行诶😢

刚才亲自测试，能发出来，自己检查版本和图片路径吧。
